### ISSUE TITLE
it's not support china regions

### ISSUE THREAD

**Issue by allen12921** [jenkinsci/ec2-fleet-plugin#103]
We found it's not support china regions as the china ec2 endpoints are different from global.
For china regions ec2 endpoint is like https://ec2.region_name.amazonaws.com.cn and the global  ec2.region_name.amazonaws.com
Could anyone pls help to add an endpoint parameter?

**Comment by terma** [comment]
wow, thx for report let check

**Comment by terma** [comment]
hi, trying to test, a few questions, do you able to setup China credentials for Plugin and see list of regions but it fails on fleets describe? or it fails imediatelly and doesn't provide region list, thx

**Comment by terma** [comment]
China regions support added in [1.6.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.6.0) China region should in region list starting from this version if some regions are missed you can specify a custom endpoint in the configuration.

Please ping if you still see some problem, thx

**Comment by terma** [comment]
Closing, feel free to reopen if you have questions.

**Comment by allen12921** [comment]
thx, man it's fixed
