### ISSUE TITLE
Dynamically detect amount of build slots per node based on instance type

### ISSUE THREAD

**Issue by Bryksin** [jenkinsci/ec2-fleet-plugin#106]
When we use spot fleet - we define multiple configurations of instances types which are satisfying our spot fleet
basically in spot fleed might be an entyre zoo of different instance types and statically define a number of build slots er slave is a bad approach, as I can get an instance with 2 cores 2 RAM or instance with 4 cores and 8 RAM, but in both cases I will have only 2 build slots per each instance type what is bad!

What I would suggest is to ask not for static numbers of build slots, but the number of Cores and RAM required per build and dynamically allocate build slots based on received instance type.
For example, if I would define in settings 1 core and 2 RAM per build, then the number of slots will be dynamically allocated as follows: 
* For 2 Core 4 Ram - 2 build slots
* For 4 core and 8 RAM - 4 build slots

**Comment by terma** [comment]
Hi, we have #32 in progress, which uses instance weight to calculate the number of executors (slots) per instance. You can read more about instance weight [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html#spot-instance-weighting) Do you think it could cover your use case?

**Comment by Bryksin** [comment]
Hi, yes, it sounds like the right approach, you can link this issue to the mentioned #32 and close this one as a duplicate

in the main time, I would love use this case of getting your personal attention and point you to the issue #43, I would imagine it is far more critical than this weights improvement, as it prevented our company from using this plugin at all! so much of my time was literally wasted setting up whole AWS infrastructure and at the end realising that plugin doesn't work and end up completely useless, as it not scaling up nor scaling down

Additionally, I spot that Jenkinsci has a project [amazon-ecs-plugin](https://github.com/jenkinsci/amazon-ecs-plugin) where ECS cluster can be also based on Spot Fleet
So it feels you guys developing kind of the same thing twice under the different sauce... would it not be beneficial to combine available human resources and develop 1 but fully functional and kick ass plugin? 
P.S. I switched for now to `amazon-ecs-plugin` hope it will work and scale up and down properly

**Comment by terma** [comment]
thx for feedback,

- closing this one as it will be covered in #32 
- added question about your case in #43
- interesting point, let me  check
