### ISSUE TITLE
"Connection refused" not treated as a transient error

### ISSUE THREAD

**Issue by gilbahat** [jenkinsci/ec2-fleet-plugin#108]
This is a timing bug: occasionally jenkins will try to connect recently launched instances before the ssh daemon is up. jenkins will obviously get a 'connection refused' error, but it should be treated as transient.

Steps to reproduce:

1. create a slave AMI that has a longer startup procedure than usual.
2. try to launch it as a worker via ec2 fleet plugin.

expected behaviour:

jenkins will retry the connection several times, even if it receives "network is unreachable" or "connection refused" errors.

observed behaviour:

upon the first try that gets a "connection refused", jenkins will consider the agent having a problem state and require manual intervention to start.

**Comment by terma** [comment]
hi, thx for a report, yep, this problem should be fixed in the scope of #76

**Comment by terma** [comment]
Fix released under version [1.8.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.8.0)

**Comment by terma** [comment]
In fact I suggest you to use version 1.8.1, I added real connect during online checking, as Jenkins could decided to postpone connection.

**Comment by terma** [comment]
Closing, feel free to reopen if you have questions or comments. thx
