### ISSUE TITLE
Incorporate Automatic Deletion of Offline Nodes

### ISSUE THREAD

**Issue by alexelent** [jenkinsci/ec2-fleet-plugin#11]
Potentially add this to the CloudNanny.java or wherever appropriate. https://github.com/samrocketman/jenkins-script-console-scripts/blob/master/cleanup-offline-slaves.groovy.

**Comment by orrc** [comment]
Script has moved here:
https://github.com/samrocketman/jenkins-script-console-scripts/blob/master/cleanup-offline-agents.groovy

**Comment by terma** [comment]
Fix was released under [ec2-fleet-1.1.8](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.1.8), feel free to reopen if you have questions or it doesn't work.
