### ISSUE TITLE
How do you configure fleet node properties?

### ISSUE THREAD

**Issue by FordyceGarfield** [jenkinsci/ec2-fleet-plugin#124]
When clicking on Configure for a Fleet Cloud node, the following error is thrown:

> No page found 'configure-entries.jelly' for class com.amazon.jenkins.ec2fleet.EC2FleetNode

An argument can be made that the user shouldn't be configuring individual nodes, but the node-specific settings (e.g. Tool Locations) do not appear under the Spot Fleet Configuration screen.

**Comment by FordyceGarfield** [comment]
Although not ideal, you can at least set the Git executable in the Job settings. The issue here is if you have a mix of Windows and Linux environments, a Job can no longer be environment-agnostic.

**Comment by terma** [comment]
can we use user data fir this case?

**Comment by imuqtadir** [comment]
I'm closing the issue as we have not heard back from you. Please feel free to reopen the issue by adding more details.
