### ISSUE TITLE
Plugin does not scale up when needed

### ISSUE THREAD

**Issue by JoseThen** [jenkinsci/ec2-fleet-plugin#125]
I am currently using version `1.9.2`.

I have 2 cases where Scaling up does not go into effect.

1. Jenkins Plugin does not scale up automatically when I set the minimum cluster to 2 when I am starting out with 0 nodes/instances.

- To get around this I had to set the target to `2` in AWS or run enough builds where the Jenkins Plugin scales up to 2 nodes.

2. Once I have at least 2 nodes running (the minimum for the cluster), if I run enough jobs where the executors for the current nodes fill up and a queue begins to form, there is no scale up.

My current configurations is:

**Minimum Cluster Size:** 2
**Maximum Cluster Size:** 20
**Number of Executors:** 5
**Max Idle Minutes Before Scaledown:** 2
**Connect Using Private IP:** true
**Maximum Init Connection Timeout in sec**: 60

Checking `AWS Cloudtrail, Jenkins logs, or the Spot Request history` there is never any information about scaling nodes up.

**Comment by rjtferreira** [comment]
I started noticing this same issue on multiple jenkins that we have even with different plugin versions.

I'm having the exact same problem with the version `1.1.9`

On a different Jenkins I tried to upgrade to the latest versions (both Jenkins and ec2-fleet-plugin) and still find the same issue :slightly_smiling_face:

**Comment by terma** [comment]
interesting, could you please help me with logs:

1. Do you see any logs with ```excessWorkload =```?
1. Any exception in log related to plugin?

**Comment by JthenG9** [comment]
1. Looking through the logs there have been no `excessWorkload` mentions.
2. No exceptions pop up.

This is what I have been getting in the logs repeatedly:

`Jenkins Spot Fleet [ec2-fleet ci-k8s tooploox] start
Jul 25, 2019 1:18:33 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
Jenkins Spot Fleet [ec2-fleet ci-k8s tooploox] described instances: [REDACTED, REDACTED]
Jul 25, 2019 1:18:33 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
Jenkins Spot Fleet [ec2-fleet ci-k8s tooploox] Described terminated instances [] for [i-0428257e0e912ab31, i-07717ca4998d0cb43]
Jul 25, 2019 1:18:33 PM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Jenkins Spot Fleet [ec2-fleet ci-k8s tooploox] # of current Jenkins nodes:5
Jul 25, 2019 1:18:33 PM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Jenkins Spot Fleet [ec2-fleet ci-k8s tooploox] Fleet (ec2-fleet ci-k8s tooploox) contains instances [REDACTED, REDACTED]
Jul 25, 2019 1:18:33 PM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Jenkins Spot Fleet [ec2-fleet ci-k8s tooploox] Jenkins contains dying instances []
Jul 25, 2019 1:18:33 PM FINER com.amazon.jenkins.ec2fleet.EC2FleetCloud
Jenkins contains fleet instances [i-07717ca4998d0cb43, i-0428257e0e912ab31]
Jul 25, 2019 1:18:33 PM FINER com.amazon.jenkins.ec2fleet.EC2FleetCloud
Current Jenkins nodes [REDACTED, REDACTED, REDACTED, REDACTED, REDACTED]
Jul 25, 2019 1:18:33 PM FINER com.amazon.jenkins.ec2fleet.EC2FleetCloud
New fleet instances []
Jul 25, 2019 1:18:33 PM FINER com.amazon.jenkins.ec2fleet.EC2FleetCloud
Missing fleet instances []
Jul 25, 2019 1:18:33 PM FINER com.amazon.jenkins.ec2fleet.EC2FleetCloud
Terminated fleet instances []`

**Comment by sdhoka** [comment]
Hello @terma ,
I am able to reproduce the issue. My environment details are as follows
Jenkins 2.121.2
Ec2-fleet plugin 1.8.1 (saw similar issue with 1.9.2)
- Executors: 1
- Min cluster size: 0
- Max cluster size: 2

Steps to reproduce
1. Trigger the first build on spot fleet, assuming no nodes exist
2. I see `excessworkload = 1`, plugin will scale up by 1 node and complete the build
3. Allow the plugin to scale down and destroy the node
4. Now, trigger another two builds so that they gets added to the queue
5. I did not see any mentions of `excessworkload` so far
6. Trigger the third build in queue and I see `excessworkload = 1` in the log, should be 3
7. The plugin scales up to 2 nodes(max) and runs builds

**Comment by terma** [comment]
@sdhoka, @JthenG9 

Short intro: ```excessworkload``` happens when Jenkins ask the plugin to provision new capacity, it's the first line in plugin provision logic. That means if you don't see it, Jenkins decided to do not request additional capacity. Jenkins provision logic pretty smart in a way that it's trying to wait a little bit before request cap, to avoid over-provision, could use usual build time for this.

There are two groups of factors for Jenkins decision: first is internal Jenkins logic, which I think should work fine. Second: plugin, as it's trying to avoid overprovision and tells Jenkins to assume started **but not yet connected** EC2 instances assumed as available capacity.

To reduce the scope of the investigation, you can disable the second group of factors (connection) by setting in plugin configuration ```Maximum Init Connection Timeout in sec``` to ```0``` restarting Jenkins or deleting or present nodes.

**Comment by sdhoka** [comment]
@terma 
Thanks for the prompt response. I tried to set `Maximum Init Connection Timeout` in sec to 0 but still ran into the same issue.  However, disabling `Only running instances`  option and restarting Jenkins  appears to have to resolved the issue. If this option is checked, the plugin does not modify spot fleet requests capacity on aws  after the first build unless we have enough number of builds in the queue. I'm not very familiar with the plugin codebase so can't determine what might be causing this.
@JthenG9 Could you try the above workaround to check if it works for your case as well?

**Comment by JthenG9** [comment]
These are my notes at my second testing:
**Minimum Cluster Size:** 4
**Maximum Cluster Size:** 10
**Number of Executors:** 5
**Max Idle Minutes Before Scaledown:** 2
**Connect Using Private IP:** true
**Maximum Init Connection Timeout in sec**: 0

1. Started out with **0 nodes**. I set the above configuration and reset Jenkins.
2. I then started a job to only run on the `ec2-fleet` label. I then began to see `excessworkload = 1` in the logs. 
3. I then began to spam the job build and  ran enough jobs to need more than 1 node. It took some time probably a minute or 2 but then Jenkins began to request `excessworkload = 5`.
4. Jenkins now had 4 new nodes that took care of all the jobs.
5. I then built around 30 jobs, the nodes began to fill up executors and a queue started to form. No new nodes requests (no `excessworkload`)
6. As those jobs were waiting I thought maybe it might just need more, so I triggered another 30 jobs on top of the above step. No new nodes loaded.

Would my issue be related to the way Jenkins load balances jobs? Has there been reports of this plugin : https://wiki.jenkins.io/display/JENKINS/Least+Load+Plugin causing issues?

**Comment by terma** [comment]
to all,

Since we have some many questions around ```plugin doesn't scale up``` I think it's time to explain a little bit how does it work, and ask the big question about that.

### Intro

The current implementation of the plugin fully depends on Jenkins scale-up strategy. **Plugin scales up capacity only by Jenkins request.** The plugin can decide to don't scale-up. if Jenkins requested but cannot scale-up without Jenkins request. The plugin doesn't have other than ```max fleet size``` logic to skip scale-up. And no ```excessworkload``` in Jenkins log means no request to plugin from Jenkins!

### Jenkins scale-up

One of the main goals for default Jenkins scale-up strategy is **avoiding capacity spikes**. That's why you don't see immediate capacity increasing when you just run tons of jobs. By default Jenkins is trying to postpone capacity scale-up as much as possible, so existent nodes could deal with queue. In other words, Jenkins focus on throughput, but not execution latency. Direct result for this is a small bill.

### Possible solution

In the modern world, this approach could be too conservative as usually, we expect a fast result. To do that plugin could override default Jenkins scale-up strategy and do provision almost immediately. The downside will be higher AWS bill versus default strategy.

### Question

Do you prefer fast allocation time versus a small bill?

Please put :+1: for this comment if you want to have a choice in plugin configuration to use default Jenkins scale-up or custom fast allocation.

**Comment by Dmitry1987** [comment]
I think the quick scale up makes sense as usually the instances are billed per minute, and the builds are "1 build per 1 instance", so if one instance builds 10 jobs in 10 hours, is same as 10 jobs spawn 10 servers, and complete in 1 hour. It will be the same in terms of billing but faster feedback loop for the developers (which is the most expensive resource in most cases, dev time per hour equals a large instance per month bill =) ). So, I'm voting +1 to fast scale up option.

**Comment by schmutze** [comment]
> instances are billed per minute

per second ;)

**Comment by Dmitry1987** [comment]
I'm having other errors when it doesn't scale  
![image](https://user-images.githubusercontent.com/9369080/62750912-94341980-ba16-11e9-9a22-1d44fafbcbe5.png)

the log has this 

```
Aug 08, 2019 7:54:53 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] start
Aug 08, 2019 7:54:54 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] fleet instances: [i-0019e2e6dd5d608fa]
Aug 08, 2019 7:54:54 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] jenkins nodes [i-0019e2e6dd5d608fa]
Aug 08, 2019 7:54:54 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] jenkins nodes without instance []
Aug 08, 2019 7:54:54 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] described instances: [i-0019e2e6dd5d608fa]
Aug 08, 2019 7:54:54 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] terminated instances []
Aug 08, 2019 7:54:54 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] new instances []
Aug 08, 2019 7:54:56 PM INFO com.dubture.jenkins.digitalocean.DigitalOceanCloud canProvision
canProvision ec2-fleet :: false
Aug 08, 2019 7:54:56 PM INFO com.dubture.jenkins.digitalocean.DigitalOceanCloud canProvision
canProvision ec2-fleet :: false
Aug 08, 2019 7:54:56 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] excessWorkload = 1
Aug 08, 2019 7:54:56 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] start
Aug 08, 2019 7:54:57 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] fleet instances: [i-0019e2e6dd5d608fa]
Aug 08, 2019 7:54:57 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] jenkins nodes [i-0019e2e6dd5d608fa]
Aug 08, 2019 7:54:57 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] jenkins nodes without instance []
Aug 08, 2019 7:54:57 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] described instances: [i-0019e2e6dd5d608fa]
Aug 08, 2019 7:54:57 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] terminated instances []
Aug 08, 2019 7:54:57 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] new instances []
Aug 08, 2019 7:54:57 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] to provision = 1
Aug 08, 2019 7:54:57 PM WARNING com.amazon.jenkins.ec2fleet.EC2FleetCloud warning
FleetCloud [ec2-fleet] provisionInternal failed
com.amazonaws.services.ec2.model.AmazonEC2Exception: Fleet Request: sfr-66fce1c4-0ca3-4513-90d5-c09d4f283d66 is not a modifiable fleet request type. (Service: AmazonEC2; Status Code: 400; Error Code: FleetNotInModifiableState; Request ID: 5d8fda82-8119-4760-b767-039c5c7b6aa6)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:22045)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:22012)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:22001)
	at com.amazonaws.services.ec2.AmazonEC2Client.executeModifySpotFleetRequest(AmazonEC2Client.java:18106)
	at com.amazonaws.services.ec2.AmazonEC2Client.modifySpotFleetRequest(AmazonEC2Client.java:18077)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.provisionInternal(EC2FleetCloud.java:335)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud$1.call(EC2FleetCloud.java:295)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud$1.call(EC2FleetCloud.java:292)
	at hudson.model.Queue._withLock(Queue.java:1438)
	at hudson.model.Queue.withLock(Queue.java:1299)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.provision(EC2FleetCloud.java:292)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:729)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:332)
	at hudson.slaves.NodeProvisioner.access$900(NodeProvisioner.java:63)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:823)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Aug 08, 2019 7:54:57 PM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@5809cd8 failed
com.amazonaws.services.ec2.model.AmazonEC2Exception: Fleet Request: sfr-66fce1c4-0ca3-4513-90d5-c09d4f283d66 is not a modifiable fleet request type. (Service: AmazonEC2; Status Code: 400; Error Code: FleetNotInModifiableState; Request ID: 5d8fda82-8119-4760-b767-039c5c7b6aa6)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:22045)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:22012)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:22001)
	at com.amazonaws.services.ec2.AmazonEC2Client.executeModifySpotFleetRequest(AmazonEC2Client.java:18106)
	at com.amazonaws.services.ec2.AmazonEC2Client.modifySpotFleetRequest(AmazonEC2Client.java:18077)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.provisionInternal(EC2FleetCloud.java:335)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud$1.call(EC2FleetCloud.java:295)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud$1.call(EC2FleetCloud.java:292)
	at hudson.model.Queue._withLock(Queue.java:1438)
	at hudson.model.Queue.withLock(Queue.java:1299)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.provision(EC2FleetCloud.java:292)
Caused: java.lang.IllegalStateException
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.provision(EC2FleetCloud.java:300)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:729)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:332)
	at hudson.slaves.NodeProvisioner.access$900(NodeProvisioner.java:63)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:823)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by terma** [comment]
don't forget ```per second/min``` is true only for linux based, windows will be per hour.

**Comment by terma** [comment]
@Dmitry1987 please correct your spot fleet configuration, as described in #131

**Comment by smastrorocco** [comment]
We are seeing same behavior where it doesn’t scale when needed. This is making this almost unusable as it blocks too many builds.

**Comment by JthenG9** [comment]
@smastrorocco then you should vote on this comment: https://github.com/jenkinsci/ec2-fleet-plugin/issues/125#issuecomment-519368220

**Comment by Spenser309** [comment]
I'm having an issue with a weighted fleet.

Min: 0
Max: 10
Scale by weight: true

Fleet Instance Types:
m5.xlarge weight 1
m5.2xlarge weight 2
m5.4xlarge weight 4

 Typically I'll get an m5.2xlarge instance with capacity of 2 when I launch a job. Then I'll start launching more jobs 

When Jenkins tries to scale up it increments target from 1 to 2 but this doesn't result in a new node being launched because it already has a capacity of 2. So the jobs linger not really being worked on.  Is there a way to address this issue?

**Comment by ryanrupp** [comment]
I don't think this is the plugin's problem but if anyone has any insights or has seen this before we're having issues with delays going from 0 to 1 node (we allow scaling down to 0 worker nodes). This is after updating to Jenkins 2.176.3 and taking the latest version of the fleet plugin. I don't think it's the plugin necessarily due to the absense of the `excessWorkload` logging as mentioned above. Basically we had a scenario like:

1) Scaled down overnight to 0 nodes
2) Job queued at 8:00AM
3) We don't see `excessWorkload` message until 8:37

The comment about the plugin just owning this and being more aggressive would probably fix the issue but I'm also not sure why Jenkins isn't triggering a scale up request in this case given it has 0 nodes/executors available to it with 1 item in the queue - I understand for some other scaling it takes into account that maybe a job will end soon so don't aggressively scale up workers when they'll shortly free up but when it's 0 workers this shouldn't apply. We have the master node set with 0 executors as we do all building on worker nodes. I can't say I saw this issue before I upgrade so may be just a bug of sorts.

**Comment by terma** [comment]
No delay provision now is available in [1.13.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.13.0) just check in configuration ```No Delay Provision Strategy```

It significally improve response time of Jenkins for new load for additional price.

**Comment by muhajirdev** [comment]
It's still not working with my ec2 spot fleet. How do I debug this?

**Comment by terma** [comment]
@muhajirdev can you share jenkins logs, or do you see any exception in jenkins logs?

**Comment by fo2rist** [comment]
Hey @terma I'm still having similar issue with plugin v2.0.1

I have more than 3 jobs waiting in the queue and 2 permanent nodes with 3 executors on each (fully loaded with 6 running jobs) + AWS fleet configured to have min fleet size of 0 and max of 1 to spin up one extra node if needed.
`No delay provision strategy` is turned off but I'm waiting for more than 5 minutes (with default timeout of 180 sec) and nothing is provisioned yet.

Logs
```
Apr 21, 2020 6:29:07 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] jenkins nodes without instance []
Apr 21, 2020 6:29:07 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] terminated instances []
Apr 21, 2020 6:29:07 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] new instances []
Apr 21, 2020 6:29:15 PM INFO com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy apply
currentDemand 3 availableCapacity 0 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)
Apr 21, 2020 6:29:16 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] start
Apr 21, 2020 6:29:17 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] fleet instances []
Apr 21, 2020 6:29:17 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] described instances []
Apr 21, 2020 6:29:17 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] jenkins nodes []
Apr 21, 2020 6:29:17 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] jenkins nodes without instance []
Apr 21, 2020 6:29:17 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] terminated instances []
Apr 21, 2020 6:29:17 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
FleetCloud [ec2-fleet] new instances []
Apr 21, 2020 6:29:25 PM INFO com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy apply
currentDemand 3 availableCapacity 0 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)
```
Am I missing something? Tried to turn on no delay provisioning, didn't help (do I need to restart?)

**Comment by Dmitry1987** [comment]
hello from 2023!!! Same issue on latest jenkins and ec2fleet versions, heeeeelp!

**Comment by battlesnake** [comment]
Same, here with an entire AWS region at my disposal and 3-4 digit quotas for some instance types, but builds via EC2 Fleet are queuing for a single instance.

**Comment by Dmitry1987** [comment]
I just love pinging this thread because I was here in 2019 lololol 
![image](https://github.com/jenkinsci/ec2-fleet-plugin/assets/9369080/7e4ae94d-0b64-475d-85d0-dd5f6fc07bc1)

OG 🚀

**Comment by Dmitry1987** [comment]
is this being maintained by the way or requires adoption? things are changing and plugins like these need updates
