### ISSUE TITLE
When plugin terminated workers, can't build any Jenkins job

### ISSUE THREAD

**Issue by fruch** [jenkinsci/ec2-fleet-plugin#128]
I have ~50 workers in a fleet, i.e. min = 0, max = 50

and when the plugin in in the middle of stopping the node, Jenkins is not usable, and build command is timing out

can the termination and modification of the fleet can be done in bigger batches ? and not one by one ? since the whole process is kind of killing Jenkins ?

**Comment by terma** [comment]
hi, interesting, looks like termination process is really complicated, plus plugin waits until node will be disconnected [code](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java#L470)

we probably can do that async, let me check

**Comment by terma** [comment]
btw, how do you know tgat problem inside termination workflow, any logs, will be useful for solution

**Comment by fruch** [comment]
@terma, I don't have the logs, but it was clearly this plugin.
I'm a bit afraid to run it to again, it took our jenkins server to it's knees, and I don't have more setups to play with. (nor the time to create such)

I'm going to a vacation today, when I'm back, I might able to try it again (when people less using the jenkins), any specific logs need ? or needs to be enabled that would help ?

**Comment by terma** [comment]
have a good vacation ))) in fact I'm on vacation too, but I have some time try to reproduce, will trycouple of ideas. 

If entire Jenkins freezed, could it be not enought memory?

**Comment by terma** [comment]
hi, finally I made it, version [1.11.2](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.11.2) should help you, it provides near ```0``` lock time for Jenkins, and is doing all staff outside of Jenkins cycle. I paid special attention to termination, not it's done in batch so you it will terminate ```*``` amount of instances in one shot.

Since change is big, as I rewrite all plugin cycle, feedback will be really good. Will close issue, feel free to open it if questions/problems etc.

**Comment by fruch** [comment]
@terma thanks a lot, I'll try taking it next time I'm trying my jenkins job (it a bit dormant, since I didn't want to hog our jenkins setup, and my focus was somewhere else)

**Comment by fruch** [comment]
@terma want to report that I've took it for a test drive, and it's works much much better now.
improved considerably 
thanks you very much

**Comment by terma** [comment]
@fruch nice to hear that, thx a lot for checking.
