### ISSUE TITLE
Error of FleetNotInModifiableState when everything seems configured correctly

### ISSUE THREAD

**Issue by Dmitry1987** [jenkinsci/ec2-fleet-plugin#131]
I had 1 node initially running all the time, but then decided to make "min 0 max 5" in settings, the node disappeared, and new builds do not create a node.
I see this in errors:

```
Aug 09, 2019 2:17:37 PM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@5809cd8 failed
com.amazonaws.services.ec2.model.AmazonEC2Exception: Fleet Request: sfr-66fce1c4-0ca3-4513-90d5-c09d4f283d66 is not a modifiable fleet request type. (Service: AmazonEC2; Status Code: 400; Error Code: FleetNotInModifiableState; Request ID: a5a9d6f7-ec01-4c6e-afca-ee9e0d85e2de)
```

I took the IAM role from the example and followed all steps I think. What am I missing here?

**Comment by terma** [comment]
Hi, 

EC2 Fleet (EC2 Spot Fleet) supports 3 types of fleet, ```request```, ```instant``` and ```maintain``` https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-fleet-configuration-strategies.html#ec2-fleet-request-type

Only for last one EC2 Spot Fleet will maintain capacity, and launch new instances if existent will be terminated. 

EC2 Fleet plugin can work only with ```maintain``` type of fleet, as it requires stable capacity. I will update our documentation to explicitly mention that.

**Comment by terma** [comment]
Doc was updated.

**Comment by terma** [comment]
I fixed a little bit plugin configuration page, starting from version [1.10.2](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.10.2) it will not show fleets with unsupported type by default

**Comment by Dmitry1987** [comment]
ok thank you!
