### ISSUE TITLE
Allow run some command to check is slave node ready to work

### ISSUE THREAD

**Issue by bozaro** [jenkinsci/ec2-fleet-plugin#134]
AWS reports `running` state before spot fleet node is actually ready to work.
Ubuntu by default allows incoming SSH connections before systemd complete boot.

As result we have:
- spot fleet starts new node;
- ec2-fleet-plugin see `running` node and run Jenkins slave before node is complete boot;
- some systemd service on boot stage drops all ssh connections;
- Jenkins slave lost connection to node and fail current task.

Ideally we need to wait boot completion by custom script. In out case it would be like:
```
set -ex

# Wait for complete boot startup
while [ "$(systemctl is-system-running)" == "starting" ]; do date; sleep 5; done

# Ensure boot is completed without errors
systemctl is-system-running
```

**Comment by terma** [comment]
User data cannot be used to implement this feature. As EC2 instance doesn't have dedicated state for ```userData``` execution and from AWS API point of view instance state will be ```running``` but ```userData``` could be still in progress.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html

**Comment by bozaro** [comment]
Looks like we found solution: `Launch agent agents via SSH` has advanced option `Prefix Start Agent Command`.
This option is concatenated with agent start command.
We try to set this option to: `while [ "$(systemctl is-system-running)" == "starting" ]; do date; sleep 5; done && systemctl is-system-running && ` and its seems to works.

**Comment by terma** [comment]
hm, that's interesting solution, I prefer it versus custom code in plugin. Will revert my changes for now, if you see that SSH prefix doesn't work, we can add it back.

**Comment by terma** [comment]
btw, I added your solution into documentation https://github.com/jenkinsci/ec2-fleet-plugin#preconfigure-slave

thx for contribution

**Comment by terma** [comment]
going to close, feel free to reopen in case of questions or problems. thx
