### ISSUE TITLE
Reduce log noise from polling done by CloudNanny

### ISSUE THREAD

**Issue by ryanrupp** [jenkinsci/ec2-fleet-plugin#141]
This would be an enhancement but I was trying to troubleshoot why when we had scaled down to 0 that a subsequent queued item took 40 minutes until Jenkins changed the target node size to 1. Anyway, the logging from `CloudNanny` that executes every 10 seconds calling `EC2FleetCloud.updateStatus` generates a decent amount of log noise which makes it harder to find interesting events (when things actually changed). Example of just polling when we had scaled down to 0 (nothing happening at that point in time):

```
Sep 18, 2019 8:00:01 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] fleet instances: []
Sep 18, 2019 8:00:01 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] jenkins nodes []
Sep 18, 2019 8:00:01 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] jenkins nodes without instance []
Sep 18, 2019 8:00:01 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] described instances: []
Sep 18, 2019 8:00:01 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] terminated instances []
Sep 18, 2019 8:00:01 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] new instances []
Sep 18, 2019 8:00:11 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] start
Sep 18, 2019 8:00:11 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] fleet instances: []
Sep 18, 2019 8:00:11 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] jenkins nodes []
Sep 18, 2019 8:00:11 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] jenkins nodes without instance []
Sep 18, 2019 8:00:11 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] described instances: []
Sep 18, 2019 8:00:11 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] terminated instances []
Sep 18, 2019 8:00:11 AM com.amazon.jenkins.ec2fleet.EC2FleetCloud info
INFO: FleetCloud [ec2-fleet] new instances []
```

Anyway my suggestion to adjust `EC2FleetCloud.updateStatus` logging is for some (all?) of these skip logging (or log as debug) if nothing has changed e.g. terminated/new instances can be skipped if the array is empty. Not sure described instances needs to be logged unless it can differ from jenkins nodes in some way. It would be nice to not log anything basically if no change is detected so the log info level logging just focuses on interesting events (status changes).

**Comment by terma** [comment]
hi, thx for point I think its fine to skip those lines, will take a look. About actual scaling problem. Plugin totally depends on Jenkins and by default Jenkins is trting to avoid scale. You can fix that by enabling no delay strategy for plugin in plugin configuration starting from version https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.13.0

**Comment by garyjyao1** [comment]
👍
