### ISSUE TITLE
Test Connection button on configure screen does not test with newly supplied credentials

### ISSUE THREAD

**Issue by jarrodspiga** [jenkinsci/ec2-fleet-plugin#15]
Steps to re-produce:

- Fresh deployment of Jenkins with the ec2-fleet plugin installed;
- Instance profile for the Jenkins instance has no ec2 permissions configured, IAM User has ec2:* permissions defined in IAM as well as a secret key/access key id;
- During configuration of plugin at Manage Jenkins > Configure Jenkins, set the "AWS Crendentials" (sic: there's a typo here that also needs to be fixed) as the access key id & secret key created above. Fill out the rest of the form then hit "Test Connection". This fails with "You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request ID: xxxxxxxxxxxx)"
- Add the ec2:describeSpotFleetInstances permission to the Instance profile role. Repeat "Test Connection" and "Success" is displayed.

**Comment by cyphus** [comment]
I ran into this as well. When I first added the credentials it worked, but after I created a different spot fleet and reconfigured the plugin to use that instead, it stopped working. Temporarily adding full administrator access to the jenkins user did not help - the credentials are definitely not being used.

I think attaching the Spot instance management policies to the Instance profile role is the better way to go. That way there's no need to manage a jenkins user and credentials separately.

**Comment by terma** [comment]
probably duplicate #71

**Comment by terma** [comment]
Looks like two different issues:

@jarrodspiga I don't think this is an issue with the plugin, it cannot work without permission, so first failed to try looks ok for me. Do you expect different behavior?

@cyphus in your case did you just change one fleet on another?

**Comment by cyphus** [comment]
@terma yes, the only change I made was to update the spot fleet instance to connect to a different spot fleet.

**Comment by terma** [comment]
@cyphus fixed in a release [1.2.1](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.2.1) please try if you have time, thx

**Comment by terma** [comment]
going to close issues, feel free to open if you still have problem or questions, thx
