### ISSUE TITLE
need a way to limit use of EC2 fleet to time-range "working hours" or way to temporarily disable the fleet

### ISSUE THREAD

**Issue by cloph** [jenkinsci/ec2-fleet-plugin#152]
Currently there is no way to disable a EC2 fleet configuration, it doesn't allow to set the maximum workers to 0 and doesn't have a dedicated activation toggle.

There should be a way to limit the creation of instances to working hours / a time-of-day range. (e.g. only create workers from 7am to 7pm, but don't bother creating instances during the night or similar)

Rationale: larger patch series submitted at the end of the workday don't need to have their results returned ASAP. If the results are available the next morning all is OK, no need to spend money on EC2 instances for that if the permanent workers will cope with the queue just fine.

**Comment by fedevegili** [comment]
I just built a groovy script that achieves this.

Here's the code: https://gist.github.com/fedevegili/71075d85a07761167903903a63ce2874
 
It's working with the latest version of the plugin, just create a jenkins job that runs from time to time and execute it.

**Comment by peanderson2016** [comment]
I am struggling to get this to actually update the "live" plugin settings. 
I can run the script and the fleet settings in `/configure` get updated but not the `EC2 Fleet Status` or the actual ASG in AWS.

Any thoughts?

**Comment by peanderson2016** [comment]
Seems like adding in the following kicks things into gear: 
```
new_cloud.setStats(new FleetStateStats(new_cloud.getStats(), minSize))
  
new_cloud.provision(null, 0)
```

**Comment by zdtsw** [comment]
gist from fedevegili is (most likely) based on 1.16.2 release, need to revisit it if you are using 2.3.2 @peanderson2016

**Comment by zdtsw** [comment]
as for the real "kick in" I think only happens when any new jobs matching the labels to the fleet, that will make the real changes for number of EC2.
like:  Jenkins new job => plugin reads config => send by cloudformation => update ASG/spot desire => updates EC2
