### ISSUE TITLE
Can we add an option to use the display name of the instance instead of instance-id for the agents connected in a cluster

### ISSUE THREAD

**Issue by sivabaisani** [jenkinsci/ec2-fleet-plugin#155]
We assign a Tag "Role = JenkinsAgent" for each node created in the spot cluster, and then in the user data script a AWS query that gives the Name tags for each host with the "Role = JenkinsAgent" tag and we use the bash script to assign serial name tags for each instance based on the result from the query. Like JenkinsAgent01, JenkinsAgent02, etc., We also use the script to set the hostname same as the name tag. Can we have an option to use the Display name instead of AWS instance-id for the nodes connected.

**Comment by imuqtadir** [comment]
Just to clarify more on details here: You have a tag (Key:Name, Value:<HOSTNAME>) attached to the instance and you wish to display these tag value: <HOSTNAME>. Is my understanding correct?

**Comment by sivabaisani** [comment]
yes that's correct. This tag represents the hostname of the instance.
