### ISSUE TITLE
Excess capacity isn't immediately pruned when max size is decreased in settings

### ISSUE THREAD

**Issue by ianfixes** [jenkinsci/ec2-fleet-plugin#157]
### To reproduce:
1. Create new spot request maually for use in Jenkins
2. Add fleet to Jenkins via this plugin, scaling from 1-4
3. (Fleet is added.  At some point it scales up to 4 nodes)
4. Remove fleet; add "new" fleet to Jenkins -- same one -- but now scale from 1-2
5. (Fleet is added.  Remains at 4 nodes indefinitely)
6. Reboot Jenkins just in case
7. (Remains at 4 nodes)

### Expected behavior:
* If newly-added fleet is greater in size than the max, automatically scale it down to the max size.
* i.e. Fleet size immediately becomes 2 nodes

### Actual behavior:
* Fleet remains at the previous max size -- 4 in this case -- even though queue has been empty for 6x the scale-down timeout

## Versions
* Jenkins `2.190.2`
* EC2 Fleet Jenkins Plugin `1.16.1`

**Comment by terma** [comment]
Point in case of fix: we could use ```Max Idle Minutes Before Scaledown``` to check if instance not executed but time is passed could be deleted. Special case when ```Max Idle Minutes Before Scaledown``` is small, so we can delete instance which just online and was not able to start handle load, as we count instance time starting when instance provided but not yet online so connection time will be counted as instance time.

**Comment by ianfixes** [comment]
I think it might also be useful to see whether there are any active builds and/or the build queue length.  If nothing is building when the plugin starts its idle timers (or however it does that), then it might be OK to just stop the instances.  If there is anything in the queue, assume that it was a hot restart and leave existing build agents alone.

**Comment by akrasnov-drv** [comment]
I also face the issue when the fleet is recreated in Jenkins, even with exactly the same configuration. All spots that were in use become suspended or offline but not removed.
Looks like the plugin keeps a list of requested instances, and uses it to remove those instances when the condition in config is met
But when the configuration is recreated, the list is likely purged, so the plugin doesn't remember the instances it got before.
Please correct me if I'm wrong.
