### ISSUE TITLE
Feature request: Test AWS permissions as part of "test connection"

### ISSUE THREAD

**Issue by ianfixes** [jenkinsci/ec2-fleet-plugin#158]
I had previously submitted a documentation patch related to proper AWS permissions:
https://github.com/jenkinsci/ec2-fleet-plugin/pull/56/files

This documentation appears to have been removed from the README.

I think it would be better to provide a check for proper permissions as part of the "Test Connection" button in the plugin configuration.  I assume this would be done best by querying the permissions of the user, not by something like attempting to "modify" the spot request to its same values.  This way, you have a test not only that the fleet can be used but that the entire plugin will function as expected.

**Comment by terma** [comment]
- Current documentation asks about ```"ec2:*"``` which covers all permissions
- That's a good call about ```Test Connection``` we could leverage AWS-SDK ```dryRun``` to try call all required operation on fleet or ASG to check permissions. ```dryRun``` does real call but don't to actual work just check permissions.

**Comment by terma** [comment]
PR is welcome =)

**Comment by ianfixes** [comment]
I didn't see a `CONTRIBUTING.md`, can you supply some info on what I should do for a development environment, style guide, and how to test any edits I make?

Also, re: `ec2:*` I think it would be better to list out what the minimum permissions are.  There are a _lot_ of EC2 permissions, and I think it would be wise to not grant all of them https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonec2.html

**Comment by terma** [comment]
About permissions. This policy recommended by AWS documentation https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#spot-fleet-iam-users

**Comment by ianfixes** [comment]
I think "recommended" is a strong word.  From that page (my emphasis):
> The `ec2:*` grants an IAM user permission to call all Amazon EC2 API actions. **To limit the user to specific Amazon EC2 API actions, specify those actions instead.**

And from https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege (again, my emphasis):
> When you create IAM policies, follow the standard security advice of granting least privilege, or granting only the permissions required to perform a task. **Determine what users (and roles) need to do and then craft policies that allow them to perform only those tasks.**

To find the minimum set of permissions, I just looked at AWS CloudTrail for the `jenkins_service_account` user that the plugin is configured to use (you can modify this URL to show the username that is relevant to you): https://console.aws.amazon.com/cloudtrail/home?region=us-east-1#/events?Username=jenkins_service_account

I set the time range for 24h of normal use and downloaded the results to `event_history.json`. Then I used this one-liner in ruby to find the unique events:

```irb(main):022:0> require 'json'
=> true
irb(main):023:0> puts JSON.pretty_generate(JSON.parse(File.read('/path/to/event_history.json'))["Records"].map { |e| e['eventName'] }.uniq)
[
  "DescribeSpotFleetInstances",
  "DescribeSpotFleetRequests",
  "DescribeInstances",
  "CreateTags",
  "TerminateInstances",
  "ModifySpotFleetRequest"
]
=> nil
```

I don't think it's bad to say `ec2:*` as a way to get people started with this plugin, but I think the documentation should (somewhere) answer the question of "what are the minimum AWS privileges required to use this plugin"

**Comment by imuqtadir** [comment]
I'll take a stab at it.
