### ISSUE TITLE
Spot instances can be now stopped and started: Plugin should allow to stop spots when idle

### ISSUE THREAD

**Issue by Puneeth-n** [jenkinsci/ec2-fleet-plugin#165]
https://aws.amazon.com/about-aws/whats-new/2020/01/amazon-ec2-spot-instances-stopped-started-similar-to-on-demand-instances/

**Comment by terma** [comment]
Interesting. Wondering what could be real world use case.

**Comment by Puneeth-n** [comment]
Currently, the plugin terminates an instance when there is an idle timeout. The plugin can be modified so that it stops the instance rather than terminate and restart the instance when required. This is a huge advantage when relying on docker cache to speed up builds in huge mono repos.

**Comment by Puneeth-n** [comment]
my bad! it is not yet available for fleets. closing the issue.

**Comment by terma** [comment]
While Fleet doesn't support this I think it could be achievable by ```UserData```

**Comment by terma** [comment]
One of solution for ```UserData``` https://github.com/atramos/ec2-spotter/tree/master/classic

**Comment by terma** [comment]
Btw have you tried https://aws.amazon.com/efs/ it's NFS, so will be shared cross instances

**Comment by terma** [comment]
One more specific for Docker Cache https://runnable.com/blog/distributing-docker-cache-across-hosts

**Comment by Puneeth-n** [comment]
> Btw have you tried https://aws.amazon.com/efs/ it's NFS, so will be shared cross instances

Yes we were using EFS before but the time required to determine the docker context (with an optimized .dockerignore) was so high compared to EBS, we abandoned it.
