### ISSUE TITLE
Add aws sdk proxy support

### ISSUE THREAD

**Issue by rubroboletus** [jenkinsci/ec2-fleet-plugin#166]
Our Jenkins host is on Intranet and needs to use proxy for any Internet communication. All other plugins are using Jenkins proxy settings without problem, but this one is not even trying to use aws java sdk proxy settings.

**Comment by terma** [comment]
Hi, could you help me with example of plugin which support proxy? How do you configure proxy, in plugin settings?

**Comment by terma** [comment]
Example for code fix: how to use proxy in Jenkins https://github.com/jenkinsci/ec2-plugin/pull/90/files

**Comment by terma** [comment]
Ok Jenkins proxy configuration support added starting from [1.17.2](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.17.2) thx a lot for report

**Comment by terma** [comment]
Feel free to reopen in case of questions or problems, thx
