### ISSUE TITLE
spot instance in jenkins

### ISSUE THREAD

**Issue by harishkolanu235** [jenkinsci/ec2-fleet-plugin#181]
is possible that after trigger the job if node is not available than spot instance should create and build the job in that spot instance.
if yes please suggest me how to do

**Comment by imuqtadir** [comment]
I'm not sure I understand. The plugin would increase the target capacity of the Spot Fleet and launch new instance if there exists a job in the queue. You don't need to do anything special for it. Please follow *README* to setup the plugin and you should be good to go.

**Comment by imuqtadir** [comment]
Feel free to reopen the issue if this didn't help or solve your issue.
