### ISSUE TITLE
Setting for "Maximum Cluster Size" being ignored in 1.17.3 (but only by a few hosts)

### ISSUE THREAD

**Issue by ianfixes** [jenkinsci/ec2-fleet-plugin#183]
`Jenkins ver. 2.190.2` and ec2-fleet plugin [version `1.17.3`](https://updates.jenkins.io/download/plugins/ec2-fleet/1.17.3/ec2-fleet.hpi)

My cluster settings are minimum of 1, maximum of 8.  
<img width="662" alt="Screen Shot 2020-04-23 at 9 38 37 AM" src="https://user-images.githubusercontent.com/583459/80105397-8c85b800-8546-11ea-9a37-bc623e3294fb.png">

After rescanning a repository (which triggered about 50 new builds), the cluster scaled up to 10 machines.  
<img width="356" alt="Screen Shot 2020-04-23 at 9 39 39 AM" src="https://user-images.githubusercontent.com/583459/80105411-91e30280-8546-11ea-9ffc-28bda141b419.png">

If they matter, here are the advanced settings:
<img width="411" alt="Screen Shot 2020-04-23 at 9 42 21 AM" src="https://user-images.githubusercontent.com/583459/80105597-ceaef980-8546-11ea-8fdf-c723c4615818.png">

Expected behavior: limit of 8 machines in the cluster
Actual behavior: the cluster size was set to a _target_ size of 10

**Comment by ianfixes** [comment]
Other anecdata about cluster size with a very full build queue:
* With max=8, I got 10 
* With max=16, I got 22
* With max=24, I got 26

**Comment by terma** [comment]
I think this fix should help you. EC2 Spot Fleet doesn't update target capacity until modification will be done, as result for minute or so, target capacity remains old after update, this fix will stop using updated target capacity until fleet status will not be active

[2.0.2](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-2.0.2)

**Comment by prasannadesai** [comment]
@terma I have been using ec2 spot fleet plugin for quiet some time, I have noticed weird kind of issue wherein if I maintain min cluster size and after that at times Jenkins fails to clear the workspace and job fails, to overcome this I have to disconnect Jenkins slave node and relaunch it again and it works like charm after relaunch. Is there any way to overcome this? as this puts dependency on a person every-time if this happens

**Comment by imuqtadir** [comment]
@prasannadesai I don't think it's related to this issue. Feel free to reopen if it is. If not, can you please open a new issue with steps to replicate?

**Comment by prasannadesai** [comment]
@imuqtadir After debugging it in and out, I got the issue i,e while launching ec2 instance with a AMI using spot fleet, the AMI which I took had some old Jenkins remote jar file, that was reason Jenkins slave node was failing to clear the workspace.
How i fixed this is I created new AMI clearing all old remote jar file, and it working beautifully
