### ISSUE TITLE
Scale Executors By Weight -- is weight ignored when setting target size or am I making a mistake?

### ISSUE THREAD

**Issue by ianfixes** [jenkinsci/ec2-fleet-plugin#184]
I decided to explore the "Scale executors by weight" feature, currently using version `1.17.3`.  It doesn't work the way I would have expected.  

The tooltip says:

----
When it's checked, plugin consumes instance weight information provided by Launch Specification and uses it to scale node number of executors from configuration field `Number of Executors` **Note** current implementation doesn't support Launch Template only Launch Specification

Example (here instance type from launch specification match with launched instance type):

Number of Executors | Instance Weight | EffectiveNumber of Executors
-- | -- | --
1 | 1 | 1
1 | 0.5 | 1
1 | 0.1 | 1
10 | 0.1 | 1
1 | 1.5 | 2
1 | 1.44 | 1

----

My intended setup is to encode the number of executors I want on a given instance type as the weight.  So an `m4.xlarge` might have 3 executors, `m4.2xlarge` might have 6, and so on.  So I set the weights in the spot request to 3 and 6 as appropriate, set the `Number of Executors` to `1`, and as expected when an `m4.xlarge` gets added to the fleet it displays 3 executors.

The problem I am seeing is that the cluster does not scale up .  Ordinarily (without the weight option) if I want a fleet of 10 instances, I set max cluster size to 10.  But with weighted fleet, if I want those same 10 instances then I have to put max cluster size at 30.  That's no problem, that makes sense.

The problem is that the "target" spot fleet size seems to be getting set as a number of instances, when it should really be set as a target weight.  So the scaling target was 10, but AWS only allocated 4 instances to meet that weight.

If I don't use a weighted spot fleet, and set `Number of Executors` to 3, I get perfect desired behavior -- cluster scales up immediately if there are builds in the queue.  What am I doing wrong here?  How can I troubleshoot?

**Comment by haedaal** [comment]
similar issue here!

+ in my case, #executor on double size node does not scale up

so for example, with #executor 1, on c5.2xlarge with weight 1, I expect jenkins runs only 1 job at once.
then on c5.4xlarge where I set weight of 2, I expect jenkins runs 2 jobs at maximum in parallel

but what I'm seeing is in both case, jenkins runs only 1 job at a time

are you experiencing same problem? or only capacity issue?

**Comment by ianfixes** [comment]
You are right about the weighted capacity, I think I figured that out after writing up this issue.  But what threw me off is that I was still in a situation where I was seeing the build queue grow instead of the fleet scaling up.  That didn't happen with the un-weighted spot fleet setup, and I'm not sure if that's by design or a mistake on my part somewhere.

**Comment by haugenj** [comment]
Gotcha, is this a problem you're still seeing? I'm wondering if this could've been resolved since version 1.17.3 or if it's something that still needs to be investigated

**Comment by ianfixes** [comment]
We had to just switch back to un-weighted fleets and call it a failed experiment.  I can test it out the next time we upgrade and report back though -- sounds like it might not be something I'm doing wrong.  Can you describe what the normal "scale up" behavior should be, or how I'd know whether the plugin thinks the build queue is too long?

**Comment by haugenj** [comment]
In the logs you'll see something like `INFO: currentDemand 2 availableCapacity 0 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)`. This shows that Jenkins is aware of the pending jobs, but there's no capacity allocated that can handle it.

By default Jenkins waits some amount of time before actually doing the scale up operation, though I don't know exactly where that's set. If you use the "No Delay Provision Strategy" that's a part of this plugin we override the default and it should try to scale up right away.

I don't think using weighted capacity should affect the scale up in any way though. As far as I can tell the executors are scaled by the weights after the new node has already come online ([code link](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java#L692-L698))

**Comment by ianfixes** [comment]
Aah -- I should have mentioned that.  We _are_ using the "no delay provision strategy", which is why the lack of scaling up was noticeable. But we're still on `1.17.3` so I'll have to upgrade and report back.

**Comment by haugenj** [comment]
In the effort of tidying up, I'm going to close this issue since it's gone stale. Feel free to reopen if the problem shows up again
