### ISSUE TITLE
Jenkins offlines build slaves with running jobs within scaledown period?

### ISSUE THREAD

**Issue by ZillaG** [jenkinsci/ec2-fleet-plugin#187]
Using Jenkins v2.164.3 and plugin v2.0.2

I created spot fleets in AWS to use as Jenkins build slaves, and then in Jenkins configuration, I added an "Amazon EC2 Fleet" to use the spot fleets. I set the "Max Idle Minutes Before Scaledown" to 60 mins, and expect that Jenkins to ONLY offline a build slave if no job has been running on it for the last 60 mins. However, Jenkins still does offline them even if a job has been running within the 60-min period. Some of our integration test jobs run longer than 60 mins, and the slaves that they're running on get offlined. Is this a bug or a misunderstanding on this setting on my part?

**Comment by imuqtadir** [comment]
Your understanding regarding ``Max Idle Minutes Before Scaledown`` is correct. The plugin will terminate the node only when it has been idle for more than ``Max Idle Minutes Before Scaledown`` while considering minimum and maximum cluster size. Is this a recurring issue? Can you share the steps to replicate along with the plugin configurations you have in place so we can dive deeper into this?

**Comment by imuqtadir** [comment]
Just checking in, are you able to respond to our questions?

**Comment by ZillaG** [comment]
This may have been the case where AWS was reclaiming the spot instances since either they ran out of these particular instance types I was requesting, and/or someone over-bid my maximum spot price.
