### ISSUE TITLE
Jenkins unable to execute jobs on replaced spot instances or scaled instances

### ISSUE THREAD

**Issue by junydania** [jenkinsci/ec2-fleet-plugin#189]
Been having this problem of Jenkins master not able to connect to replaced spot instances or new instances added during scale up.

Whenever a spot instance is terminated & replaced, jobs fail to run on the new instance slave spot instance with this error:

**hudson.remoting.Channel$CallSiteStackTrace: Remote call to i-09e3xxxxxxxxxxxx**
**Caused: java.io.IOException: Remote call on i-09e3xxxxxx failed**

Would appreciate any help in resolving this

**Comment by imuqtadir** [comment]
Ideally, it should re-queue the failed build if you have ```Disable build resubmit``` option NOT enabled. Please provide us with around 10 minutes of plugin logs when the interruption happened along with plugin configuration and any other detail which would help us debug or reproduce this.

**Comment by junydania** [comment]
@imuqtadir  Sure will provide the logs when this re-occurs. Thanks

**Comment by imuqtadir** [comment]
I'm resolving this for now. Please feel free to reopen when you have additional details.
