### ISSUE TITLE
Don't show canceled spot fleet requests

### ISSUE THREAD

**Issue by rodlogic** [jenkinsci/ec2-fleet-plugin#21]
Filter out the canceled spot fleet requests from the list when configuring the plugin.

**Comment by ianfixes** [comment]
Even if you have to achieve this with a checkbox for "only active instances" or a freeform textbox for me to paste in the spot fleet ID that I want, this is becoming increasingly necessary -- I have hundreds of cancelled requests that make it difficult to configure this plugin.

Could they at least be sorted by status (specifically, "active") before being sorted alphabetically by their hexadecimal-based identifier?

**Comment by terma** [comment]
Feature implemented and released in [1.2.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.2.0)
