### ISSUE TITLE
Jobs stalling indefinitely on a node started by the plugin

### ISSUE THREAD

**Issue by cw-shubham** [jenkinsci/ec2-fleet-plugin#212]
Hello
Jenkins version 2.222.3
Plugin version 2.0.2

We have been using this plugin for some time and have found this useful but have encountered a problem.
Sometimes jobs on a node start stalling. I am able to run script on the script console properly but any job running on the node stalls.
It is the same case for new jobs being allocated to the node.
We are using an AMI to make the node. A node made using the same AMI separately added to jenkins works perfectly. 

What could be the issue?

**Comment by imuqtadir** [comment]
By stalling, do you mean the node is in idle however the job is not getting picked up or is the job being picked up however not being executed on the node? Are you able to verify the corresponding EC2 instance is Active and in healthy state? Are there any steps which will help me replicate this issue?

**Comment by cw-shubham** [comment]
Thanks @imuqtadir for quick reply
1- the node accepts jobs but the code doesn't run. Any pre existing jobs which were running stop running too
2- I was able to ssh into the node as well as run scripts on the script console
3- I am not able to understand the reason so recreation steps would be difficult.

**Comment by imuqtadir** [comment]
Thanks for the details. Can you please verify if the jenkins slave agent is working on the EC2instance?

**Comment by cw-shubham** [comment]
Running scripts on the script console works so I think it should be.

**Comment by imuqtadir** [comment]
I want to see if the slave agent is running. Please ssh and run following command:

```
[root@ip-xxxx~]# ps aux | grep jenkins
root      1564  0.0  0.0 119416   984 pts/1    S+   19:54   0:00 grep --color=auto jenkins
ec2-user  5517  0.0  0.0 119968  2884 ?        Ss   17:08   0:00 bash -c cd "/tmp/jenkins-00419d81" && java  -jar slave.jar
ec2-user  5649  0.0  0.0 119848  2808 ?        S    17:08   0:00 /bin/sh -xe /tmp/jenkins6594622639406669025.sh
```

Does this issue exists across all the nodes and all the jobs? What is the frequency of this issue, how often do you see it happening?

**Comment by imuqtadir** [comment]
Resolving this issue as we have not heard back from you. Feel free to re-open if you are still encountering this issue with additional info.
