### ISSUE TITLE
Instances are terminated before ASG lifecycle hook runs

### ISSUE THREAD

**Issue by amainwaring** [jenkinsci/ec2-fleet-plugin#216]
I am trying to have the scale-in trigger an SNS->Lambda->Jenkins job to remove the scaled-in worker from AD/DNS. What I am finding is that by the time the Lambda runs the instance has already been terminated.

![image](https://user-images.githubusercontent.com/20444883/94717789-ca211500-031e-11eb-8af4-15be0c950e8d.png)
![image](https://user-images.githubusercontent.com/20444883/94686580-080b4280-02f9-11eb-8751-078e79ed15c1.png)
![image](https://user-images.githubusercontent.com/20444883/94686691-2bce8880-02f9-11eb-93d7-7b2fcdb6b979.png)

I think what is happening is that the ec2-fleet plugin is terminating the instance, but I think instead it should be removing the scale-in protection from the instance, reducing the desired capacity on the ASG, and letting the ASG terminate it.

Any help would be appreciated!

**Comment by imuqtadir** [comment]
EC2-Fleet plugin sets the target capacity based on the job queue however, the instance is terminated by calling TerminateInstance API by the plugin after verifying that the instance has been idle for more than allowed ```maxIdle``` time and there are no current job being executed by the instance. The plugin does not let the ASG terminate the instance. Let me know if you have any questions

**Comment by amainwaring** [comment]
Thanks for the response! What I want to do is run a Jenkins job when the instance is terminated. Currently we do this with other ASG instances with a terminating lifecycle hook but that is not working on the ASG I'm using for the EC2-Fleet plugin because the instance is already terminated by the time the lifecycle hook is run.

I think, instead of calling TerminateInstance API, you could just remove the scale-in protection on that ASG instance and reduce the desired capacity, which would allow the ASG to handle the termination of the instance and allow that lifecycle hook to run while the instance is still online.

Another option might be a feature request to trigger a Jenkins job when an instance is created/terminated. I've tried using scripts to run while an instance is shutdown but those are a little fragile and may not run if an instance is terminated unexpectedly. I'm currently using a scavenger job to monitor for when a worker is removed but having the process be part of the plugin would be nicer.

Thanks again!

**Comment by imuqtadir** [comment]
@amainwaring Unfortunately, relying on ASG to terminate the instance is not feasible with current implementation. It would not be an easy change to do. If you want we can create an issue for the same to see if we have enough interest to support this in future. 

> Currently we do this with other ASG instances with a terminating lifecycle hook but that is not working on the ASG I'm using for the EC2-Fleet plugin because the instance is already terminated by the time the lifecycle hook is run.

The node is first removed from Jenkins and set to not accept any further jobs and will be removed after small gap (depends on Cloud init interval). Probably that is the reason you are not able to run any job on the terminated node. 

> Ive tried using scripts to run while an instance is shutdown but those are a little fragile and may not run if an instance is terminated unexpectedly.

Do you mean terminated unexpectedly by Spot ITIN? You can monitor the ITIN and take actions appropriately. You need to add the script on init level 0, which is the halt level. The script will be also invoked on shutdown and termination.

**Comment by amainwaring** [comment]
Sorry, it's a Windows worker. During the creation (userdata) I join it to the domain, and when I shutdown the machine I'd like for it to be removed from Active Directory and DNS. With other ASGs we accomplish this with the terminating lifecycle hook that I explained above but in this case doesn't work because the instance is terminated first, outside of the ASG.

**Comment by modbender** [comment]
This is a very required feature, our companies agent contains some important files and we need it to be moved. Please add this feature.
