### ISSUE TITLE
First update not done, skip termination

### ISSUE THREAD

**Issue by webminster** [jenkinsci/ec2-fleet-plugin#226]
This with EC2 Fleet Jenkins Plugin 2.2.0, and Jenkins LTS 2.249.2...

This morning I had a builder instance that stayed up overtime.  The following in the logs:

2020-10-30 15:23:25.210+0000 [id=38]    INFO    c.a.j.e.IdleRetentionStrategy#check: Check if node idle i-0fa6611c8e322a10f
2020-10-30 15:23:25.210+0000 [id=38]    INFO    c.a.j.e.IdleRetentionStrategy#isIdleForTooLong: Instance: FleetCloud i-0fa6611c8e322a10f Age: 3151526 Max Age:1800000
2020-10-30 15:23:25.210+0000 [id=38]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] Attempting to terminate instance: i-0fa6611c8e322a10f
2020-10-30 15:23:25.210+0000 [id=38]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] First update not done, skip termination
2020-10-30 15:23:28.270+0000 [id=39]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] start
2020-10-30 15:23:29.076+0000 [id=39]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] fleet instances: [i-0fa6611c8e322a10f, i-022c7e7150493f0d1]
2020-10-30 15:23:29.822+0000 [id=39]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] described instances: [i-0fa6611c8e322a10f, i-022c7e7150493f0d1]

What does "First update not done, skip termination" mean?  How can I debug why ec2fleet is failing to terminate the obviously too old instance?

**Comment by gaforester** [comment]
I'm having the same issue. It started about 6 days ago. This with EC2 Fleet Jenkins Plugin 2.2.0, and Jenkins LTS 2.249.3.

`Nov 11, 2020 6:55:05 PM INFO com.amazon.jenkins.ec2fleet.IdleRetentionStrategy check
Check if node idle i-0e5178cd85e2dxxx
Nov 11, 2020 6:55:05 PM INFO com.amazon.jenkins.ec2fleet.IdleRetentionStrategy isIdleForTooLong
Instance: JenkinsEc2RegressionFleet i-0e5178cd85e2dxxxx Age: 5409829 Max Age:600000
Nov 11, 2020 6:55:05 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
JenkinsEc2RegressionFleet [ecs_fleet test regression ecs_slave] Attempting to terminate instance: i-0e5178cd85e2dxxxx
Nov 11, 2020 6:55:05 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
JenkinsEc2RegressionFleet [ecs_fleet test regression ecs_slave] First update not done, skip termination`

I see in the source that means stats is null. How can I figure what's going on? I've created new clouds in Jenkins, new spot fleets and restarted about a dozen times.

**Comment by imuqtadir** [comment]
`First update not done` usually happens when Jenkins plugin is not aware of state of world in AWS. It should ideally be in sync after `Cloud Status Interval` which is configurable as `Cloud Init Interval` within plugin configuration. This occurs when you first setup Jenkins plugin or when you update the plugin settings. Can you verify if you still see this error even after the cloud init seconds interval?

**Comment by webminster** [comment]
It's been 13 days, and I no longer have the logs or full context... I had the "Maximum Init Connection Timeout in sec" as 300, and the "Cloud Status Interval in sec" as 10 (there is no "Cloud Init Interval" exactly).  However the messages went on longer than either.  IIRC this only went away when everything was restarted.

**Comment by imuqtadir** [comment]
Yes, ideally the message should go after `Cloud Status Interval in sec`. I'll try to check for scenarios where this might be an issue however if it occurs again then please let me know the series of steps. In past I have heard this usually happen after updating plugin configuration however I still don't have a way to replicate it.

**Comment by gaforester** [comment]
I have cloud status interval set to 10s. I've downgraded, upgraded, created new fleets, removed plugin and re-installed, deleted clouds and re-created, and restarted Jenkins about 100 times. Still same issues. I still get the `First update not done, skip termination` no matter what I do. Still won't scale down. Here's my current config for one of my clouds...
`clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: true
      awsCredentialsId: "jenkins_voltron"
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "jenkins-spot-ssh"
          launchTimeoutSeconds: 240
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      disableTaskResubmit: false
      fleet: "sfr-e56d9e25-b07b-4772-83a0-b2453fe03xxx"
      fsRoot: "/home/jenkins/fs"
      idleMinutes: 30
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "spot_fleet d0 d1 t2"
      maxSize: 8
      minSize: 0
      name: "JenkinsEc2Fleet"
      noDelayProvision: false
      numExecutors: 2
      oldId: "ed7b9381-5f2f-4767-9140-fcd4ad38bxxx"
      privateIpUsed: true
      region: "us-east-1"
      restrictUsage: false
      scaleExecutorsByWeight: false`

Here's an example of the logs I'm still seeing...
`2020-11-13 04:22:27.761+0000 [id=43]	INFO	c.a.j.e.IdleRetentionStrategy#check: Check if node idle i-0e809f5e86e1997e3
2020-11-13 04:22:27.761+0000 [id=43]	INFO	c.a.j.e.IdleRetentionStrategy#isIdleForTooLong: Instance: JenkinsEc2Fleet i-0e809f5e86e1997e3 Age: 2570505 Max Age:1800000
2020-11-13 04:22:27.761+0000 [id=43]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: JenkinsEc2Fleet [spot_fleet d0 d1 t2] Attempting to terminate instance: i-0e809f5e86e1997e3
2020-11-13 04:22:27.761+0000 [id=43]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: JenkinsEc2Fleet [spot_fleet d0 d1 t2] First update not done, skip termination`

**Comment by pauxus** [comment]
I encountered the same today. Of 4 configured FleetCloud, only one was affected. 

Interestingly, when calling `scheduleToTerminate`manually via script console, the first update message does not occur, the instance is terminated, so in that case, stats does is not null.

The only thing that might make sense is that somehow the Fleet Instance is continuosly reloaded somehow (leading to the transient field being null)

**Comment by pauxus** [comment]
After a restart, scale down works again. However, this left 50 Agents running idle for hours...

**Comment by pauxus** [comment]
same as #177

**Comment by pauxus** [comment]
@gaforester Just for the record: how big is your Jenkins instance (number of jobs, etc), and what memory settings do you use?

**Comment by imuqtadir** [comment]
Thank you. This is all useful. If you happen to encounter this bug again, I want to have access to more logs. Specifically around `EC2FleetCloud#info: FleetCloud [ec2-fleet] start`. Also, are you using  `No Delay Provision Strategy` option and is the bug related to enabling it? Meanwhile I'll take a look into this and see if I'm able to reproduce.

**Comment by imuqtadir** [comment]
My assumption after diving deep into code and the info provided is is that for some reason the `CloudNanny` thread which triggers the `update()` every `Cloud Status Interval in sec` is stuck and hence restarting Jenkins would fix this. This thread is responsible for updating the fleet state within Jenkins. It would be helpful if someone could answer these questions:

1.  I understand that this issue revolves around instances not being terminated. However, this thread is also responsible for provisioning. Are you able to provision/scale up more instances when you encounter this issue?
2.  Do you see `start` within your logs? This should show up every `Cloud Status Interval in sec`. This value is set within your plugin settings.
3. Do you notice any deadlock or any useful info within your thread dump while this issue is happening? You can check your thread dump here under /threadDump ex: http://localhost:5005/jenkins/threadDump

**Comment by pauxus** [comment]
Not sure right now about 1) and 3), since the error is not occurring right now. 

But the cloud nanny was definitely running. We have four different fleets configured (different configurations), and the three other ones got their nanny runs as expected, and since this is a single Timer / thread for all fleets, I don't think this is what's happening.

**Comment by pauxus** [comment]
As to NoDelayProvisioning: if I remember correctly, this happened with our windows slaves, which are the ones without NoDelayProvisioning, but I am not one hundred percent sure. I will have a look at the logs later.

**Comment by imuqtadir** [comment]
I was able to replicate this bug. 🎉 

I'm working for a fix on this now.

**Comment by imuqtadir** [comment]
I'll cut a release next week once I get approval on my PR.

**Comment by lloydchang** [comment]
Thank you @imuqtadir
