### ISSUE TITLE
Introduce `Maximum Total Uses` parameter

### ISSUE THREAD

**Issue by mwos-sl** [jenkinsci/ec2-fleet-plugin#232]
Same way EC2 plugin has. It does not allow to schedule more builds on a given agents if the counter reaches the limit.

**Comment by mwos-sl** [comment]
This one: https://github.com/jenkinsci/ec2-fleet-plugin/issues would be even better I would say. Having both would be a dream :)

**Comment by brandon-fryslie** [comment]
We would like to replace the `ec2-plugin` with this plugin, but we rely on the `maxTotalUses` parameter heavily.  We only run 1 build per instance so the environment is 100% consistent between builds.  Without the ability to limit the total number of builds per ec2 instance using this plugin is a non-starter unfortunately.  Just chiming in to say this feature would be very much appreciated!

**Comment by mwos-sl** [comment]
As above. In our case we rely on this strongly when it comes to machines that are used for benchmarking. So lack of this feature is actually blocker for us too :( 
And in all the other places we've got this parameter set to small values too, to ensure machines are rotated to enforce fresh state.
Apart of that there are some compliance use cases, such as _being required to replace instances on a schedule due to internal security policies or external compliance controls._

**Comment by imuqtadir** [comment]
I'll look into this and give you an update this week.

**Comment by imuqtadir** [comment]
I was testing my changes and came across this scenario. Assume a fleet of size: 1 instance and total builds for that instances are exhausted (maximum total uses) however the user has set minimum capacity of cluster as 1. What should be expected behavior here?

**Comment by imuqtadir** [comment]
I have put out PR for it. I'll cut a release once I get approval and merge the code.
