### ISSUE TITLE
Introduce "Minimum number of spare instances"

### ISSUE THREAD

**Issue by mwos-sl** [jenkinsci/ec2-fleet-plugin#233]
It is slightly different than "Minimum number of instances". EC2 Plugin has both btw. It ensures there are always `n` available agents, up to "Maximum number of instances". This is to lower time a new build waits to provision a machine.

**Comment by imuqtadir** [comment]
Thanks for your valuable suggestion. I think this might be useful to customers. We could prioritize it (like any issue) if we have more customers asking for this feature.

**Comment by driverpt** [comment]
@mwos-sl , are you referring to WarmPools ?

**Comment by mwos-sl** [comment]
_Something like this_, but I'm not sure if this feature should be handled on AWS side (by ASG) in this case.
If I understand warm pools correctly, they just keep some ec2 booted up, but there is no jenkins agent provisioned and no jenkins init script run until jenkins master ssh to such node and executes initialisation.
Also calculation of size of warm pools seems strange.

And in my case I need some `Minimum number of instances` jenkins agents connected and 100% ready to handle work. Thus I think it's more about the plugin to set desired capacity properly.

**Comment by imuqtadir** [comment]
@mwos-sl Just elaborating my understanding here about minimum spare number of instances. We would always have `minimum spare instances` as idle at any given time. Let's say we have new builds come up, we would let the spare instances pick up the work however go ahead and launch new instances to satisfy the minimum spare instances criteria. These spare instances will not be terminated if they are idle for more than configured idle time because doing so would breach `minimum spare instances` count. Let me know if my understanding is correct.

**Comment by fipciu1996** [comment]
@imuqtadir 

Yeah, you understand correctly. It will be really helpful especially when we had faced the situation right now when sometimes we are waiting for a couple of minutes for spawning the instance and it will help us to make our builds faster.

For now, as a workaround, we modified the configuration to keep instances idle for one hour and we've increased the number of maximum builds, but it isn't cost-effective.

**Comment by h-okon** [comment]
Up. This would highly reduce time when waiting for an instance.

**Comment by mwos-sl** [comment]
@imuqtadir yes, I meant exactly this :)

Well, it would be even more awesome to have a way to force roteting those spare instances if they are working for way too long as well.  By, for example, introducing one more optional parameter `spareInstanceIdleMinutes` (next to the existing `idleMinutes`, with default to infinity), which would force replacing an instance even if it is "spare", and new one is created in its place. So for example configuration in my case could be:
```
idleMinutes: 3
spareInstanceIdleMinutes: 1440
spareInstances: 1
```
which would be cost efficient for "non-spare instances", would keep always 1 spare instance (up to maximum number of instances), but also would force rotating instance, even if it is currently a "spare" one. And that would give us 100% guarantee we're not having workers with AMI/tools much older than 24 hours, which is important for us from compliance and security perspective.

But all in all, having a simplified version of it, the way you described and without what I described above, would be a huge thing anyway :)

**Comment by letmeseeit** [comment]
Definitely useful feature. In the landscape I am working with waiting for new instances allocation can significantly increase build times. Having pool of "always" ready spots would solve my issues.

**Comment by imuqtadir** [comment]
Thanks for your input. @mwos-sl I like the idea for having some mechanism to recycle these at some point, we could use `spareInstanceIdleMinutes`. For starter, we will aim to have simplified version soon and take it up from there later.

**Comment by fipciu1996** [comment]
up

**Comment by fipciu1996** [comment]
up

**Comment by fipciu1996** [comment]
up

**Comment by fipciu1996** [comment]
@imuqtadir is anything going on with that issue ? We're really looking forward for this feature

**Comment by imuqtadir** [comment]
@fipciu1996 Sorry for delay due to holidays. I have put out PR for it today. Feel free to review it.

**Comment by imuqtadir** [comment]
This should be going out in the next release which will done before EOW.

**Comment by fipciu1996** [comment]
Awesome, thanks for your help :)

**Comment by imuqtadir** [comment]
This featured was part of release 2.5.0. Please let us know your experiences. It will be valuable for us to understand your use-cases and plan upcoming features.

**Comment by letmeseeit** [comment]
That is an awesome news, thanks @imuqtadir !

**Comment by h-okon** [comment]
Really good news. Thank you very much for implementing this feature.

**Comment by mwos-sl** [comment]
Kudos! We'll check this out :)
