### ISSUE TITLE
Build Executors won't start nor connect at all, and the "Test Connection" button stopped working, when AWS Credentials is "- none -" to use the EC2 instance role.

### ISSUE THREAD

**Issue by lloydchang** [jenkinsci/ec2-fleet-plugin#252]
Hi, @imuqtadir and @haugenj,

This is observed in version 2.3.0 of ec2-fleet-plugin — I believe the issue was first introduced in version 2.2.1 of the plugin.

**Build Executors won't start nor connect at all, and the "Test Connection" button stopped working, when AWS Credentials is "- none -" to use the EC2 instance role.**

"Test Connection" button says, "Select AWS Credentials to check permissions"

The worse outcome and unintended consequences are that Build Executors for ec2-fleet-plugin won't spawn nor connect at all.

**"- none -" is a valid value for AWS credentials because README.md says to leave empty to use the EC2 instance role:**
> Configure AWS credentials, or leave empty to use the EC2 instance role
> https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/README.md#5-configure-jenkins

After skimming list of changes between versions 2.2.0 and 2.3.0, this issues seems to have been introduced in version 2.2.1 of the plugin with a commit and merge from @imuqtadir and review by @haugenj via **"Fix null for AWS Permissions"** at https://github.com/jenkinsci/ec2-fleet-plugin/pull/225

**To work around the issue, I downgraded to version 2.2.0 of the plugin.**

After downgrading to version 2.2.0, "Test Connection" button says, "Success! Skipping validation for following permissions: TerminateInstances, UpdateAutoScalingGroup"

More importantly, Build Executors will connect after downgrading to version 2.2.0

Thank you @imuqtadir and @haugenj

**Comment by imuqtadir** [comment]
Thanks @lloydchang for bringing this to our notice. I have put out PR for reverting this and will follow-up with a release after I get approval.
