### ISSUE TITLE
Jobs stalling indefinitely on a node started by the plugin

### ISSUE THREAD

**Issue by amainwaring** [jenkinsci/ec2-fleet-plugin#257]
Hello!

Our issue sounds very similar [to this one](https://github.com/jenkinsci/ec2-fleet-plugin/issues/212). From time to time a new worker will spawn but all of the jobs get stuck in the `Checkout SCM` phase. Both pipeline and freestyle jobs seem to be affected. I can select the node and run scripts via the Script Console but any job that starts on the worker gets hung up. If i terminate an existing job and let a new job run while the worker is in the stuck then that job will also become stuck, but if I reboot the worker and relaunch the agent then new jobs will complete successfully. 

Any help would be greatly appreciated!

Console output from a stuck job:
![image](https://user-images.githubusercontent.com/20444883/106465599-2d0af000-6468-11eb-8bc8-629e73c2cbbe.png)

Thread dump from stuck job: 
```
Thread #4
	at DSL.checkout(running in thread: org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution [#5841])
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.CheckoutScript.performCheckout(CheckoutScript.groovy:73)
	at DSL.stage(Native Method)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.CheckoutScript.performCheckout(CheckoutScript.groovy:72)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.CheckoutScript.checkoutAndRun(CheckoutScript.groovy:56)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.CheckoutScript.doCheckout(CheckoutScript.groovy:40)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.impl.LabelScript.run(LabelScript.groovy:43)
	at DSL.node(running on i-03b219838aa5df979)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.impl.LabelScript.run(LabelScript.groovy:42)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:589)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(ModelInterpreter.groovy:76)
	at WorkflowScript.run(WorkflowScript:1)
```

It appears like they get stuck on the flyweight executors on the master:
![image](https://user-images.githubusercontent.com/20444883/106464797-22039000-6467-11eb-843e-b005bd628605.png)
![image](https://user-images.githubusercontent.com/20444883/106464828-2f207f00-6467-11eb-957d-070db50c4fe4.png)

## Environment Details

**Plugin Version?**
2.2.0

**Jenkins Version?**
2.204.5

**Spot Fleet or ASG?**
ASG

**Using No Delay Provision Strategy?**
Yes

**Linux or Windows?**
Linux master, Windows slaves

Thanks!

Alex

**Comment by jillmon** [comment]
Hello, 
We have triaged your ticket according to our team's guidelines. We should have some time to investigate next week. Thank you for your patience.

**Comment by haugenj** [comment]
Hi @amainwaring 

It sounds like new nodes are being provisioned and the Jenkins agents are started, so I'm not sure this problem is caused by our plugin, especially since you say the jobs are getting stuck on the flyweight executors. 

Is there anything that stands out to you in the node logs? Any difference in the node logs when they are first started by the plugin versus when you restart them manually? 

I am also curious if the first job to run on a new node stalls, or if it's only subsequent ones. If it's only subsequent jobs that fail, perhaps there are cached assets or settings that are lingering from previous jobs that get cleared when the node/agent is restarted

**Comment by amainwaring** [comment]
Thanks for getting back to me! There's nothing that stands out in the node log, or in the userdata output to me; no errors and output is the same as other nodes. I'm not so sure it's necessarily the plugin either but we've only started experiencing this issue since switching the workers to the fleet plugin. If I reboot the node then I can relaunch it and jobs will continue as per normal, so it seems to me like it's something in that initial connection or how the jobs are assigned to flyweights/executors while the new worker is being built. The only other major difference that I can think of is we are now using SSH to connect the workers instead of a service running on them, so maybe it's related to that?

**Comment by haugenj** [comment]
@amainwaring have you had any luck with this?

**Comment by amainwaring** [comment]
Unfortunately not, some nodes still occasionally hang like this when they are created and I've been unable to figure out why. I'm working on getting Jenkins updated but because of different dependencies it's going to take a while.
