### ISSUE TITLE
IRSA Support

### ISSUE THREAD

**Issue by alexandrud** [jenkinsci/ec2-fleet-plugin#259]
**Is your feature request related to a problem? Please describe.**
When running jenkins in kubernetes it doesn't assume an IRSA role. Details about IRSA here: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

The web identity token and the env variables are present and readable by the user running jenkins.

Looking in cloudtrail I see the calls are made by the IAM role assigned to the EC2 instance.

**Describe the solution you'd like**
A possible reason is described here: https://github.com/aws/aws-sdk-java/issues/2136. Probably the webIdentityToken is not evaluated and used for authentication and authorization.

**Comment by haugenj** [comment]
Based on that thread we might be able to solve this simply by upgrading the aws-java-sdk version to 1.11.717 or higher, @alexandrud would you be able to test that theory? If not I'll try to pick this up sometime next week

**Comment by alexandrud** [comment]
@haugenj If you point me in the right direction I can try to help. How can I test with a higher sdk version? I'm not a developer so my java knowledge is close to none.

**Comment by haugenj** [comment]
You can adjust the dependency versions in the POM.xml file in our plugin, but after that I'm not sure how deploying a development plugin-version to Jenkins on k8s works. Right now when I test changes it's all done locally
