### ISSUE TITLE
nodes are getting disconnected after some time

### ISSUE THREAD

**Issue by akshayubale1** [jenkinsci/ec2-fleet-plugin#262]
Firstly i used 100% spot instances in my Auto scaling group with price capped at on-demand price but still the nodes were getting disconnected then i changed to 100% on-demand instances but still the nodes were getting disconnected

Please help struggling from 1 week

Below is the stack strace

16:23:48 INFO: Detected dialect: W3C
16:23:48 FATAL: command execution failed
16:23:48 java.io.EOFException
16:23:48 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
16:23:48 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
16:23:48 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
16:23:48 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
16:23:48 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
16:23:48 	at hudson.remoting.Command.readFrom(Command.java:140)
16:23:48 	at hudson.remoting.Command.readFrom(Command.java:126)
16:23:48 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
16:23:48 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
16:23:48 Caused: java.io.IOException: Unexpected termination of the channel
16:23:48 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
16:23:48 Caused: java.io.IOException: **Backing channel 'i-069d95q7ce32ebf24' is disconnected.**
16:23:48 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:214)
16:23:48 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
16:23:48 	at com.sun.proxy.$Proxy92.isAlive(Unknown Source)
16:23:48 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1150)
16:23:48 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1142)
16:23:48 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
16:23:48 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
16:23:48 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
16:23:48 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
16:23:48 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
16:23:48 	at hudson.model.Build$BuildExecution.build(Build.java:206)
16:23:48 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
16:23:48 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
16:23:48 	at hudson.model.Run.execute(Run.java:1818)
16:23:48 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:23:48 	at hudson.model.ResourceController.execute(ResourceController.java:97)
16:23:48 	at hudson.model.Executor.run(Executor.java:429)

**Comment by haugenj** [comment]
👋 @akshayubale1, The job stack trace you gave doesn't really give me anything to go off of so could you give me some more information: 
- When did this start occurring? 
- What version of Jenkins and the plugin are you using?
- Can you verify the instances are still in the autoscaling group after this error shows up and that they're not being scaled down for some external reason? You can check the activity log on the ASG or use Cloudtrail for this
- Can you provide the Jenkins logs? 
- Does this happen to all your instances? Or for all your jobs? Are there any patterns? 

I'm removing the bug label for now until we determine whether this is actually a bug caused by the plugin

**Comment by akshayubale1** [comment]
Answers to your questions

1)i have newly installed this plugin 
2)Jenkins ver - 2.176.3  and EC2 Fleet Jenkins Plugin version - 2.3.2
3)After the nodes are disconnected the job gets failed  and in the activity log of autoscaling group the instance will be terminated stating reason as because of changing  the desired capacity(as normal they are getting scaled down) 
4)the above one is the log for job stating that the instance is disconnected but not able to see the fleet node logs as they are getting terminated immediately in the jenkins ui
5)this happens for all jobs and all instances and all instance types


Some changes which i did
   1)prefix as  below
   `   aws configure set region us-east-1 && aws autoscaling set-instance-protection --instance-ids `wget -q -O - http://169.254.169.254/latest/meta-data/instance-id` --auto-scaling-group-name ec2-spot-instance-asg --no-protected-from-scale-in &&  `
  because the ec2 fleet plugin was overiding the asg settings and all instances were scale-in protected so the above one will remove as instance is logged in

**Comment by haugenj** [comment]
Scale in protection is necessary for the plugin to work, because the plugin controls terminating instances based on how long the nodes have been in a idle state. When you disable scale in protection you allow the ASG to terminate the instances, which means it can interrupt jobs

**Comment by akshayubale1** [comment]
Thank you so much now i am not facing any issues
