### ISSUE TITLE
Scale out is not reaching above 50 when the max capacity is 650 and the required no of slaves is 63

### ISSUE THREAD

**Issue by sukanyasuresh** [jenkinsci/ec2-fleet-plugin#263]
## Issue Details

I am using the ec2-fleet-plugin to try and run my build on spot instances.
The job run tests in parallel on 65 nodes. These nodes are the ones that are being launched using the plugin.
The problem is that, the scale out never goes up above 50 even when the max capacity provided is 650.
The number of executors are 1 and the maximum usage of is 1.
In asg, the min and desired count is 0 and the max is 650.
Why is the scale out not happening above 50?

**To Reproduce**
Configurations in jenkins plugin:
<img width="1087" alt="Screenshot 2021-03-18 at 3 12 22 AM" src="https://user-images.githubusercontent.com/78716853/111542463-c59acc80-8797-11eb-8f7a-89512b3bbe9b.png">

## Environment Details

**Plugin Version?**
2.3.2

**Jenkins Version?**
2.263.2

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Using No Delay Provision Strategy?**
Same behaviour when yes and no

**Linux or Windows?**
Linux

**Anything else unique about your setup?**
None

**Comment by haugenj** [comment]
You're probably limited by the service quota: https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-account-limits.html

**Comment by haugenj** [comment]
Is there any information available in CloudTrail around the time of the scaling request?

**Comment by sukanyasuresh** [comment]
@haugenj 
Thanks for the response.
How is the desired amount of instances calculated when its specified as 0?

**Comment by sukanyasuresh** [comment]
> You might be limited by the service quota: https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-account-limits.html



> You might be limited by the service quota: https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-account-limits.html

I am able to launch more than 50 instances when i specify the desired/minimum no of instances.

**Comment by sukanyasuresh** [comment]
> Is there any information available in CloudTrail around the time of the scaling request?

I dont have cloud trail logs set up but I have attached the activity log.

`
Cancelled | Could not scale to desired capacity because all remaining instances are protected from scale-in. | At 2021-03-17T21:39:22Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 35 changing the desired capacity from 50 to 35. At 2021-03-17T21:39:27Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 3 changing the desired capacity from 35 to 3. At 2021-03-17T21:39:32Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 0 changing the desired capacity from 3 to 0. At 2021-03-17T21:39:36Z group reached equilibrium. | 2021 March 18, 03:09:36 AM +05:30 | 2021 March 18, 03:09:36 AM +05:30
-- | -- | -- | -- | --
Successful | Launching a new EC2 instance: i-0018d6e0586057db7 | At 2021-03-17T21:14:18Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 47 changing the desired capacity from 0 to 47. At 2021-03-17T21:14:23Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 50 changing the desired capacity from 47 to 50. At 2021-03-17T21:14:33Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 50. | 2021 March 18, 02:44:37 AM +05:30 | 2021 March 18, 02:45:11 AM +05:30
Successful | Launching a new EC2 instance: i-062971e2b9762e646 | At 2021-03-17T21:14:18Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 47 changing the desired capacity from 0 to 47. At 2021-03-17T21:14:23Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 50 changing the desired capacity from 47 to 50. At 2021-03-17T21:14:33Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 50. | 2021 March 18, 02:44:37 AM +05:30 | 2021 March 18, 02:45:10 AM +05:30
Successful | Launching a new EC2 instance: i-055b849e3198e9fdc | At 2021-03-17T21:14:18Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 47 changing the desired capacity from 0 to 47. At 2021-03-17T21:14:23Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 50 changing the desired capacity from 47 to 50. At 2021-03-17T21:14:33Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 50. | 2021 March 18, 02:44:37 AM +05:30 | 2021 March 18, 02:45:10 AM +05:30
Successful | Launching a new EC2 instance: i-059c21c8aefa3af39 | At 2021-03-17T21:14:18Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 47 changing the desired capacity from 0 to 47. At 2021-03-17T21:14:23Z a user request update of AutoScalingGroup constraints to min: 0, max: 650, desired: 50 changing the desired capacity from 47 to 50. At 2021-03-17T21:14:33Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 50. | 2021 March 18, 02:44:37 AM +05:30 | 2021 March 18, 02:45:10 AM +05:30

`

**Comment by haugenj** [comment]
>  How is the desired amount of instances calculated when its specified as 0?

Demand is calculated by `queue size - available capacity` ([example](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java#L41)). In the default Jenkins scaling strategy it increases target capacity in multiple requests to try and avoid overscaling. In our NoDelayProvisioningStrategy we update the target capacity to the demand amount right away. There's nothing within the plugin that limits the instances to 50 though, which is why I thought this could be a quota problem. 

Could you provide the master logs for this? 

I'll try and run a test locally to see if I can get above 50 instances

**Comment by sukanyasuresh** [comment]
@haugenj Yeah i have attached it here:
[log-events-viewer-result.csv.zip](https://github.com/jenkinsci/ec2-fleet-plugin/files/6166437/log-events-viewer-result.csv.zip)

**Comment by haugenj** [comment]
I was able to get above 50 in my test.

Looking at your logs I can't find anything that stands out to me. When not using the NoDelayProvisioningStrategy it's up to Jenkins (not our plugin) to determine when to call provision. If you can find the Jenkins logs for that we can take a peek, but it might be easier to use the NoDelayProvisioningStrategy and grab the logs from that. 

Just to confirm, you have 15 pending jobs in the queue when this happens and they fail to get scheduled to an executor?

**Comment by sukanyasuresh** [comment]
> I was able to get above 50 in my test.
> 
> Looking at your logs I can't find anything that stands out to me. When not using the NoDelayProvisioningStrategy it's up to Jenkins (not our plugin) to determine when to call provision. If you can find the Jenkins logs for that we can take a peek, but it might be easier to use the NoDelayProvisioningStrategy and grab the logs from that.
> 
Okay, let me get that for you.

> Just to confirm, you have 15 pending jobs in the queue when this happens and they fail to get scheduled to an executor?

It's just one jenkins job where the number of nodes to run a stage in parallel is 63.

**Comment by sukanyasuresh** [comment]
> I was able to get above 50 in my test.
> 
> Looking at your logs I can't find anything that stands out to me. When not using the NoDelayProvisioningStrategy it's up to Jenkins (not our plugin) to determine when to call provision. If you can find the Jenkins logs for that we can take a peek, but it might be easier to use the NoDelayProvisioningStrategy and grab the logs from that.

[log-events-viewer-result (1).csv.zip](https://github.com/jenkinsci/ec2-fleet-plugin/files/6166703/log-events-viewer-result.1.csv.zip)

> 
> Just to confirm, you have 15 pending jobs in the queue when this happens and they fail to get scheduled to an executor?

**Comment by sukanyasuresh** [comment]
@haugenj 
Update:
I tried running 2 builds for this job and the scaling goes upto 110 now.
