### ISSUE TITLE
EC2 Fleet Plugin : 2.0.2 - scale up is not working  in No Delay Provision Strategy

### ISSUE THREAD

**Issue by prakashemeascm** [jenkinsci/ec2-fleet-plugin#264]
Hi Team, 

We are also facing the same exact issue (EC2 Fleet wnot scale up in "No Delay Provision Strategy" option is enabled) and we have installed the ec2-fleet-plugin:2.0.2 version.

Once Instance is having 4 executors if the instance is fully occupied even though when the job are in queue the instance are not getting provision.

It was working fine, but since last week we are facing issue.

We have seen the below log in jenkins, 
`2021-04-19 12:42:24.968+0000 [id=29]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: currentDemand 27 availableCapacity 12 (availableExecutors 12 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)`

Here below is the config for fleet plugin:
![image](https://user-images.githubusercontent.com/82818220/115239071-fe81e480-a13b-11eb-8a2d-5d5d608dfa36.png)

_Originally posted by @prakashemeascm in https://github.com/jenkinsci/ec2-fleet-plugin/issues/260#issuecomment-822441470_

**Comment by haugenj** [comment]
Hi @prakashemeascm 

Version 2.0.2 is quite old, and doesn't contain several updates we made to try and address scaling problems. Could you update to a later version and let me know if you still see this problem?

**Comment by haugenj** [comment]
Closing this since version 2.0.2 is quite old and there's a similar issue #260 that deals with the current version
