### ISSUE TITLE
Parameters of resubmitted builds are missing

### ISSUE THREAD

**Issue by mfa-inverso** [jenkinsci/ec2-fleet-plugin#265]
## Issue Details

**Describe the bug**
Sometimes our fleet instances are terminated and the resubmitted builds fail because the parameters are missing. I created a very simple pipeline job to reproduce it. The parameters have no default values. 
Build 10 has parameters:
![image](https://user-images.githubusercontent.com/62642310/114905011-c36c7200-9e18-11eb-884c-b5eeeda972ec.png)
Build 11 is the resubmitted build after I terminated the instance and it has no parameters:
![image](https://user-images.githubusercontent.com/62642310/114905069-d4b57e80-9e18-11eb-96af-cc040f41b391.png)
There even isn't a parameters section in the menu. I can also see in the console that the parameters are not set. 

**To Reproduce**
1. Create simple pipeline job that runs long enough to terminate the fleet instance 
2. run job
3. terminate fleet instance while it's running 
4. wait for resubmitted job to run 
5. check parameters section in build menu 
etc.

## Environment Details

**Plugin Version?**
2.3.2

**Jenkins Version?**
2.277.2

**Spot Fleet or ASG?**
Spot Fleet

**Label based fleet?**
No

**Using No Delay Provision Strategy?**
Yes

**Linux or Windows?**
Linux

**Anything else unique about your setup?**
No

**Comment by zipkid** [comment]
We are looking into using this plugin.
This bug is a show-stopper.
Is there any development ongoing on this plugin to fix this bug?

**Comment by allenbenz** [comment]
It appears the executor.getCurrentExecutable() result for pipeline builds is of type `org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution.PlaceholderTask.PlaceholderExecutable` and that doesn't implement Actionable.

I'm not really sure what would be the right way to get Actions out of it.

I did find a way that I think is too brittle.
For a fork of ec2-plugin in the EC2FleetAutoResubmitComputerLauncher equivalent I added
```
if (task instanceof WorkflowJob) {
  Run<?,?> runForDisplay = ((ExecutorStepExecution.PlaceholderTask) subTask).runForDisplay();
  if (runForDisplay != null) {
    int buildNumber = runForDisplay.getNumber();
    WorkflowRun failedBuild = (WorkflowRun) ((WorkflowJob) task).getBuildByNumber(buildNumber);
    if (failedBuild != null) {
      actions.addAll(failedBuild.getActions(ParametersAction.class));
      actions.addAll(failedBuild.getActions(SCMRevisionAction.class));
    }
  }
}
```
Only some actions are copied, doing all of them seems to not work, used [ReplayAction](https://github.com/jenkinsci/workflow-cps-plugin/blob/3dc80877c92b8e64efbf33fcde5b27e5334250b1/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java#L257) to determine what to include.

Again, not a suggestion to add this code, just an observation of what is going on and why parameterized pipeline builds aren't being requeued with parameters.

**Comment by haugenj** [comment]
@allenbenz thanks for finding this, I've been playing around with it a bit and condensed it down to this:
```
if (task instanceof WorkflowJob) {
    WorkflowRun failedBuild = ((WorkflowJob) task).getLastBuild();
    actions.addAll(failedBuild.getActions(ParametersAction.class));
    actions.addAll(failedBuild.getActions(SCMRevisionAction.class));
}
```

This seems to work fine in my simple tests, but I'm curious what makes you think your solution is too brittle. IMO it's at least a step in the right direction and I say we move forward with it

**Comment by allenbenz** [comment]
I think getLastBuild can return the wrong build if there are multiple in progress builds.

My concern about brittleness is me being conservative about a stack I'm unfamiliar with and being uncomfortable with runForDisplay().getNumber()

This concern should be taken very lightly as I don't know how stable those interfaces are.

**Comment by mwos-sl** [comment]
FWIW I've just noticed the same :(
In our case, default parameters are picked for a retry, which is wrong.

**Comment by mwos-sl** [comment]
Dear maintainers, please apply "stalebot-ignore" label ⬆️

**Comment by mfa-inverso** [comment]
Does that mean that this bug will not be fixed?

**Comment by haugenj** [comment]
I'll continue to work on this when I get time, I've been pulled onto other work for a while now. More than happy to accept prs for this if someone else is able to contribute in the meantime

**Comment by mfa-inverso** [comment]
@haugenj That would be great. Thanks

**Comment by morlajb** [comment]
@haugenj if there is a preliminary fix , I can help and test it

**Comment by haugenj** [comment]
@morlajb I never got further than what i described earlier with 
```
if (task instanceof WorkflowJob) {
    WorkflowRun failedBuild = ((WorkflowJob) task).getLastBuild();
    actions.addAll(failedBuild.getActions(ParametersAction.class));
    actions.addAll(failedBuild.getActions(SCMRevisionAction.class));
}
```

Inside of `EC2FleetAutoResubmitComputerLauncher`. I remember I was having trouble configuring tests that would trigger it

**Comment by mwos-sl** [comment]
Not sure if that helps, but there is plugin:
https://plugins.jenkins.io/rebuild/
they somehow gather all the parameters of a given build.

**Comment by shahmishal** [comment]
We are also running into this issue @mwos-sl suggestion looks promising, @haugenj is that something you looked at before?

**Comment by shahmishal** [comment]
Rebuilder plugin includes parameters: 
https://github.com/jenkinsci/rebuild-plugin/blob/master/src/main/java/com/sonyericsson/rebuild/RebuildAction.java#L228

EC2 Fleet plugin would need to change code in this area:
https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java#L103-L104

**Comment by imuqtadir** [comment]
I'm looking into this issue. I'll keep you all posted.

**Comment by jozenstar** [comment]
@imuqtadir Any luck so far?

**Comment by imuqtadir** [comment]
@jozenstar I'm working on trying to find the best solution to this.

**Comment by imuqtadir** [comment]
I have tested my changes and the fix works fine. I will cut a release probably before end of the week.

**Comment by jozenstar** [comment]
@imuqtadir Thanks!
