### ISSUE TITLE
Allow configuring "usage" (Only build jobs with label expressions matching this node)

### ISSUE THREAD

**Issue by abentley** [jenkinsci/ec2-fleet-plugin#27]
Now that nodes support labels, it would be nice to be able to restrict a fleet to only jobs that match their labels.  For example, I'm transitioning to a new AMI by adding a second fleet request, but I'd like to run jobs on the old AMI by default during the transition.

**Comment by fruch** [comment]
any news regarding this one ? 
I have lot of unlabeled job in my jenkins and I don't want them default to my fleet. (at least not yet)

**Comment by terma** [comment]
Hi, @abentley this features available from version [1.5.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.5.0)

I'm going to close the issue, if you have a problem with this feature or questions, feel free to reopen, thx
