### ISSUE TITLE
Remove depleted instances that used `maxTotalUses` regardless of cluster `minSize`

### ISSUE THREAD

**Issue by haugenj** [jenkinsci/ec2-fleet-plugin#271]
Instances using the `maxTotalUses` field are kept around until they hit their idle timeout limit, even if they are suspended and can't take any more work. These are wasting instance hours and should be terminated prior to their idle timeout, assuming it's non-zero (never terminate)

**Comment by amccrodan** [comment]
Thanks for opening this! The real crux of the matter (for me) is that they are also not terminated even past their idle timeout limit, if that would drop the count of instances below `Minimum Cluster Size`. Ideally the suspended wasteful one would be swapped out for a fresh instance.

**Comment by haugenj** [comment]
Looked through the code a bit more, looks like we do try and schedule these instances for termination right after they use up all their uses ([code reference](https://github.com/jenkinsci/ec2-fleet-plugin/blob/ea67792dffe5a12245bda8e77705ef4ba5b32867/src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java#L134-L136)), but the min cluster size blocks them from being added to the termination list. Need to add some logic [here](https://github.com/jenkinsci/ec2-fleet-plugin/blob/ea67792dffe5a12245bda8e77705ef4ba5b32867/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java#L697) to check for this so they'll still get added to the list

**Comment by imuqtadir** [comment]
I have pushed the code for this. It should go out in next release this week.

**Comment by imuqtadir** [comment]
Released in 2.4.1
