### ISSUE TITLE
EC2-Fleet Spot doesn't scale up to minsize

### ISSUE THREAD

**Issue by hetile-ssense** [jenkinsci/ec2-fleet-plugin#274]
## Issue Details

**Describe the bug**
When creating a fleet, the number of nodes is never increased. I created a new fleet with initial capacity at 20 waited for all the nodes to up then configured EC2-fleet. It added all the agent and they all became ready.

I've set the min size to 5 and the max to 20 and the idle scale down to 5. I purposely didn't send any pipeline to these nodes so after 5 minutes, 15 nodes were removed (and terminated) correctly.

Changing the configuration back to min 10 but nothing is happening. The history on the spot request did not receive any change and no nodes are being added. 

We are using an instance role with the added perms from https://plugins.jenkins.io/ec2-fleet/#change-log

The test connection works

**To Reproduce**
1. Create a new ec2 fleet
2. Setup the permissions
3. Increase the min size of the cluster

## Environment Details

**Plugin Version?**
2.3.3

**Jenkins Version?**
2.289.3

**Spot Fleet or ASG?**
Spot fleet

**Label based fleet?**
No

**Using No Delay Provision Strategy?**
Tried both yes and no

**Linux or Windows?**
Linux

**Anything else unique about your setup?**
We are creating the spot fleet request using terraform, with a launch template. This is not an upgrade, it's our first attempt at configuring it. I didn't run the groovy script and used the UI to set all the fields and apply and saved.

AWS's cloudtrail doesn't show any request (failed or not) after the scale down.

I also tried deleting config and aws resources and creating a spot fleet with initial target at 0, add the cloud config with 2 nodes min size and nodes never gets created.

Here is a log extract "grep -i fleet" we can see it's not removing any nodes but it's not adding any either. There was 5 agents in the fleet and I tried increasing it to 8

https://pastebin.com/raw/UkQfU37u

**Comment by haugenj** [comment]
Took a look through the code, seems that the plugin is only using minsize to prevent terminations, not to scale upwards. The assumption being that the target capacity cannot be less than the minsize, which is untrue for spot fleet. 

Thanks for finding this!

**Comment by hetile-ssense** [comment]
I know this question is super annoying to received but I'm not looking at a precise answer but something we can base our planning on. ssense wants to use this plugins but depending on the maintenance  schedule, we will look for an alternative solution while waiting for this plugin to be updated.

Based on your reply, I'm assuming that it would scale up based on load, our jenkins goes thru hundreds of PR everyday so it might actually be safe to try it.

**Comment by hetile-ssense** [comment]
sorry about that ^^ I hit the wrong button.

We receive hundreds of PR every day with multiple stages so if the scale up would happen, we might still be able to use it for our production cluster. Load usually start to pickup around 8 am so the idea was to let it scale down very low over night and it would scale when dev start pushing PR.

Based on your answer, I'm assuming it would be safe to use and it would scale up if load was happening on the cluster ?

**Comment by haugenj** [comment]
As long as you don't change minsize to a value greater than the current instance count in the fleet, it should scale up just fine. So if you want to have a minsize of 5, make sure that there are 5 instances in the fleet before saving the plugin config and we will never scale down below 5 instances. 

I think even in your example case where you changed minsize from 5 to 10 it should still scale up as jobs were queued, but it just won't preemptively adjust the cluster size to the new minsize due to missing logic

**Comment by hetile-ssense** [comment]
I can confirm that the plugin did scale up when load was sent to it 💯
