### ISSUE TITLE
EC2 fleet set to use a wrong ASG (which should not be even created)

### ISSUE THREAD

**Issue by zdtsw** [jenkinsci/ec2-fleet-plugin#275]
## Issue Details
We use Jcasc to config EC2 fleet. 
The issue we observed is even there is no name-matching ASG it still picks one.

For example, we have two jenkins controllers. One for production, one for testing. 
Each sets with different value to env. variable `AWS_FLEET_GROUP`: 
for production it is `"myproject"`
for testing it is` "myproject-test"`

Then in AWS,  we create ASG` jenkins_ec2_myproject-linux` and `jenkins_ec2_myproject-windows ` for production jenkins cluster.
To reduce cost on testing one, we only create `jenkins_ec2_myproject-test_windows`

Both production and testing using the same docker image to deploy container for jenkins controller.
When config in Jcasc, we have code like:
```
            String fleetGroup = env['AWS_FLEET_GROUP']
            fleet: "jenkins_ec2_${fleetGroup}-${platform}",
```

Everything works fine in production controller, but in testing one, from configuration, we expect to have only one EC2 Fleet "test-windows"  which set to connect `jenkins_ec2_myproject-test_windows`.
but in reality, it configed 2 EC2 Fleets. the wrongly created one "test-linux" is setting to use `jenkins_ec2_myproject-linux` 

I do not know how exactly it got to pick `jenkins_ec2_myproject-linux`  maybe by alphabet order or just regex match ASG name.
But this is causing problem when both production and staging are trying to use the same EC2 from the same ASG.

## Environment Details

**Plugin Version?**
2.3.2

**Jenkins Version?**
2.190.3

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
Yes

**Using No Delay Provision Strategy?**
Yes

**Linux or Windows?**
Jenkins controller runs in Linux container, Jenkins agents run as windows ec2

**Anything else unique about your setup?**
No

**Comment by imuqtadir** [comment]
@zdtsw Can you share the logs with me specifically around cloud formation stack creation (test-linux)? Also, share Jcasc code if possible. Feel free to conceal critical/confidential info, I want to analysis the flow of events so I could replicate it on my end.

**Comment by zdtsw** [comment]
@imuqtadir thanks for reply! here is the snippet of my code, running in init.groovy
```
Thread.start {
    try {
        String fleetGroup = env['AWS_FLEET_GROUP'] // set to "myproject-test" for staging, set to "myproject" for production
        Jenkins jenkins = Jenkins.getInstance()
        jenkins.clouds.removeAll(EC2FleetCloud)
        Map baseConfig = [
            awsCredentialId: 'aws-jenkins-ec2-fleet-credential',
            ec2Username: env['USER'],
            ec2Password: env['PASSWORD'],
            endpoint: '',
            oldId: '',
            addNodeOnlyIfRunning: false,
            alwaysReconnect: true,
            cloudStatusIntervalSec: 10,
            disableTaskResubmit: false,
            initOnlineCheckIntervalSec: 15,
            initOnlineTimeoutSec: 600,
            noDelayProvision: true,
            numExecutors: 1,
            privateIpUsed: true,
            restrictUsage: true,
            scaleExecutorsByWeight: false,
            maxTotalUses: '-1',
            fsRoot: 'C:\\JenkinsSlave',
            minSize: env['MINSIZE'].toInteger(),
            maxSize: env['MAXSIZE'].toInteger(),
            idleMinutes: env['IDLE'].toInteger()
        ]
        [
            [
                name: "${fleetGroup}-linux",
                fleet: "jenkins_ec2_${fleetGroup}-linux",
            ],
            [
                name: "${fleetGroup}-windows",
                fleet: "jenkins_ec2_${fleetGroup}-windows",
            ]
        ].each { partialConfig ->
            Map config = baseConfig + partialConfig
            EC2FleetCloud ec2FleetCloud = new EC2FleetCloud(
                    config.name, // fleetcloudname
                    config.oldId,
                    config.awsCredentialId, //deprecated filed just put here as a placeholder
                    config.awsCredentialId, //awsCredentialsId
                    config.region,
                    config.endpoint,
                    config.fleet, // fleet
                    config.labelString, // labelString
                    config.fsRoot, // fsRoot
                    new ManagedWindowsServiceConnector(config.ec2Username, config.ec2Password), // computerConnector
                    config.privateIpUsed, // if need to use privateIpUsed
                    config.alwaysReconnect, // if need alwaysReconnect
                    config.idleMinutes, // if need to allow downscale set > 0 in min
                    config.minSize, // minSize
                    config.maxSize, // maxSize
                    config.numExecutors, // numExecutors
                    config.addNodeOnlyIfRunning, // if need addNodeOnlyIfRunning
                    config.restrictUsage, // restrictUsage allow execute only jobs with proper label
                    config.maxTotalUses, // restrict how many jobs can be run on the same agent, this is not really useful in our case, use default -1 as "no limit"
                    config.disableTaskResubmit, // if disableTaskResubmit
                    config.initOnlineTimeoutSec, // timeout for new node to become online
                    config.initOnlineCheckIntervalSec, // poll every x seconds for new node availability
                    config.scaleExecutorsByWeight, // if use EC2 ASG weighting when determining available executors
                    config.cloudStatusIntervalSec, // poll AWS every x seconds for updates
                    config.noDelayProvision // if scale up as soon as there's a build in queue
            )
            // add cloud configuration to Jenkins only when Jenkins has ENABLE_EC2 set to "true"
            if (enableEC2) {
                jenkins.clouds.add(ec2FleetCloud)
            }
        }
        jenkins.save()
}
```
I am not sure what you meant by "logs around cloud formation stack creation"? is this part of the Jenkins logs when it gets started?

**Comment by imuqtadir** [comment]
@zdtsw Yes, the plugin logs should be part of the startup.

**Comment by zdtsw** [comment]
Tried to find any related startup log, but could not.... then I looked up the code, realized that we've set
```
        Logger.getLogger('com.amazon.jenkins.ec2fleet.CloudNanny').setLevel(Level.SEVERE)
        Logger.getLogger('com.amazon.jenkins.ec2fleet.EC2FleetCloud').setLevel(Level.SEVERE)
        Logger.getLogger('com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy').setLevel(Level.SEVERE)
```
but I think by using jcasc config in init.groovy it should be easily reproduce this issue, which usually wont be noticed if EC2 fleet is configed manually by UI from dropdown list

**Comment by imuqtadir** [comment]
Let us know if this solved your issue.
