### ISSUE TITLE
Spin down fleet overnight / on weekends

### ISSUE THREAD

**Issue by abentley** [jenkinsci/ec2-fleet-plugin#28]
It would be nice to be able to schedule the fleet to drop its minimum cluster size to zero during low-usage times, like overnight or on weekends.

**Comment by abentley** [comment]
I imagined that the "Minimum Cluster Size" setting would increase the fleet's target capacity if something external set it lower.  I've had experience this morning that suggests the minimum cluster size isn't actually enforced if there are no jobs, and I find it surprising.

**Comment by schmutze** [comment]
Could also use scheduled scaling for Spot Fleet:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-scheduled-scaling.html

**Comment by fedevegili** [comment]
This is a Jenkins job I've been using to change the plugin settings depending on the hour or day of the week: https://gist.github.com/fedevegili/f1a8bdcf2bc8e2f694dced7fa71c87aa.

It has been working reliably for quite a few years now.
