### ISSUE TITLE
Fleet plugin ignoring agents that exceed the age maximum which stays alive due to minimum count

### ISSUE THREAD

**Issue by nwithers-ecr** [jenkinsci/ec2-fleet-plugin#291]
## Issue Details

**Describe the bug**
When there exists a fleet agent that is being kept alive due to a minimum cluster size but exceeds the max idle minutes before scaledown, if the fleet plugin sees a new job in the queue, it will schedule a new fleet agent and terminate the already existing agent. 

**What I expect to happen**
Instead of spinning up a new agent, the fleet plugin should use the one that's already provisioned 

**To Reproduce**
- Set cloud configuration to:
```
Max Idle Minutes Before Scaledown - 10
Minimum Cluster Size - 1
Maximum Cluster Size - 10
Maximum Total Use - 1
```
- Schedule a job
- Observe fleet plugin creating a new instance instead of using the existing one

## Environment Details

**Plugin Version?**
2.3.4

**Jenkins Version?**
Image:         jenkins/jenkins:2.303.1-jdk11

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
Yes

**Using No Delay Provision Strategy?**
Both show this behavior

**Linux or Windows?**
Ubuntu focal 20.04

**Anything else unique about your setup?**
AWS gov cloud
RKE2 cluster
[output.log](https://github.com/jenkinsci/ec2-fleet-plugin/files/7173989/output.log)

**Comment by haugenj** [comment]
Likely this is happening because you've got the `maxTotalUses` field set to 1, so I would guess the idle instance had already been used for a job.

There's a related issue #271 for removing these used instances preemptively

**Comment by nwithers-ecr** [comment]
I will run a few more jobs to confirm. I didn't check to see if the instance had been used or not.

**Comment by nwithers-ecr** [comment]
I've been watching the jobs for a few days and I do believe that you're right and this is related or a duplicate of #271

**Comment by haugenj** [comment]
closing in favor of #271
