### ISSUE TITLE
EC2 Fleet not listed

### ISSUE THREAD

**Issue by alb777** [jenkinsci/ec2-fleet-plugin#292]
Need to understand if the scenario below is a bug or just a incompatible resource with the plugin unlike spotfleet or asg

**Describe the problem**
After create EC2 Fleet Request on AWS with appropriated permissions linked on instance profile
EC2 Fleet fullfiled and instance running
Install Jenkins EC2 Fleet Plugin at Jenkins master
The EC2 Fleet launcher ID from slave are not listed even "Show All Fllets" is flagged.
Besides that, ASGs and SpotFleet requests are listed on plugin mgmt. 

**To Reproduce**

- Create ec2 fleet over AWS CLI or IAAC (Terraform or CloudFormation) (not available through console)
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/manage-ec2-fleet.html

- Wait to request being fulfilled
![image](https://user-images.githubusercontent.com/75791899/134046785-a8aeaa58-45c1-4867-b5c7-07bc8cb19edb.png)

- Search for the request on jenkins EC2 Fleet Plugin
![image](https://user-images.githubusercontent.com/75791899/134046290-80fea8d3-876f-4295-a675-34d15a20c91f.png)

**Environment Details**

Plugin Version?
2.3.4

Jenkins Version?
2.249.1

Spot Fleet or ASG?
EC2 Fleet

Label based fleet?
No

Linux or Windows?
Linux

Anything else unique about your setup?
No

**Comment by haugenj** [comment]
We only show "fleet" request types, not "instance" request types. The instance requests (`sir-n65...`) are tied to fleet requests (`sfr-2df3...`) and the plugin should find the instances once you hit save and it initializes

**Comment by alb777** [comment]
> We only show "fleet" request types, not "instance" request types. The instance requests (`sir-n65...`) are tied to fleet requests (`sfr-2df3...`) and the plugin should find the instances once you hit save and it initializes

@haugenj both requests are independent, spot fleet request from screenshot is part of another workload that is not related to jenkins. 

At my reproduced scenario, EC2 Fleet request action hasn't dependency on spot fleet request, created like this doc reference:  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/manage-ec2-fleet.html

**Comment by haugenj** [comment]
Ah I see. The plugin doesn't support EC2 Fleet right now. We only support [Spot Fleet](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html) and Auto Scaling groups

**Comment by alb777** [comment]
Thank you @haugenj, there is any plan to integrate EC2 Fleet resource ?

**Comment by haugenj** [comment]
No not currently. If there's more desire for this I'll give it a higher priority, but I likely won't be able to get started on more plugin work until after re:Invent
