### ISSUE TITLE
Get insight in node's number of uses

### ISSUE THREAD

**Issue by Hildebrand-Ritense** [jenkinsci/ec2-fleet-plugin#293]
Hey, I love this great plugin and have been looking through the logs to see if I can get grips on the scaling behaviour and more specifically on the number of uses of a node.

Sometimes I wonder if the scale-down algorithm is working correctly and being able to check whether a specific node has passed the Maximum Total Uses treshold would really help. Would it be possible to either display this in the Jenkins UI, or maybe log this next to the instance's age?

Thank you!

**Comment by haugenj** [comment]
We log the remaining number of uses for an agent when a task is accepted, so you should be able to get some information right now
<img width="708" alt="Screen Shot 2021-09-27 at 12 01 29 PM" src="https://user-images.githubusercontent.com/56001173/134953569-c43bd67d-9774-4434-832e-fc284b8d3272.png">

I think adding that info to the age information in the idle check is a great idea though!

**Comment by Hildebrand-Ritense** [comment]
Ah great, I must have missed these lines while skimming through the logs.
Now running this line gives me some insight in an agent's status: `sudo tail -f -n 1000 /var/log/jenkins/jenkins.log | grep "builds left"`

**Comment by imuqtadir** [comment]
@Hildebrand-Ritense This should go out with next release 2.3.8

**Comment by Hildebrand-Ritense** [comment]
Thank you for mentioning :) this is great news and greatly benefits insight in the scaling actions.

**Comment by imuqtadir** [comment]
You are welcome! :) This was released as part of 2.4.0
