### ISSUE TITLE
Reassigning old cloud without oldId

### ISSUE THREAD

**Issue by imuqtadir** [jenkinsci/ec2-fleet-plugin#302]
## Issue Details

**Describe the bug**
Jenkins always creates a new instance of `Cloud` object each time when you save Jenkins configuration regardless of whether it had actually changed or not. Basically, Jenkins never mutates existent instance of Cloud. As a result all objects which depend on the info from cloud should start to consume new instance of this object. 

The Cloud object referenced within Computer / Node and it is imperative that the reference to Cloud object should be updated within them. 

Taking a step back, there are two ways we can modify plugin configuration.
1. UI
2. CasC

For UI, the way we handle updating cloud reference is by [placing an invisible entry](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly#L14) which is pre-populated by existing ID whenever the config page is loaded. Whenever we click save - the value of current (now old) ID which was already pre-populated is passed onto the constructor. We can easily filter the nodes/computer's which were affected using the _old_ ID and update their cloud reference to the new cloud. 

However, in case of CasC - this workaround will not work. CasC simply loads the entire YAML file and if it is missing _old_ ID field, we will not reassign the affected nodes/computer with new cloud. Thus the computers are marked as suspended when they reach their idle time however never deleted. 

**Workaround:**
To fix this, you will need to include `oldId` field in your CasC setting every time you load CasC. You can get the oldId field from your existing configuration. Go to Manage Jenkins > Configuration as Code > View Configuration. Copy just the field `oldId` with it's value to your new CasC file.
```

Example Snippet of my CasC.
      ........
      numExecutors: 1
      oldId: "bb5e2c1b-2603-4278-a862-9f59d16a52fd"
      privateIpUsed: false
      region: "us-west-2"
      ........

```

We need to find a way to avoid relying on old Id.

## Environment Details

**Plugin Version?**
2.3.1

**Comment by imuqtadir** [comment]
This was pushed as part of 2.3.7 release

**Comment by morlajb** [comment]
we just update to 2.3.7 3 days ago , and looks like the issue still exist , if you need any logs or any conf , i can try and help with this ...

**Comment by mwos-sl** [comment]
FWIW We upgraded few days ago, I already did several CasC reload on 2 of our jenkinses, and the fix seems to work on both.

**Comment by imuqtadir** [comment]
@morlajb I would advise you to restart Jenkins (not just the plugin) once. If you still encounter this issue then feel free to open a new issue. Follow the template to provide us with all the info.

**Comment by imuqtadir** [comment]
@mwos-sl I'm happy that it resolved your long standing issue. Thank you for your patience in working through this.

**Comment by morlajb** [comment]
Thanks @imuqtadir  will restart and update

**Comment by ujain6** [comment]
Hi, I restarted jenkins but still see the same issue that a new cloud is created.
