### ISSUE TITLE
No fleets appear

### ISSUE THREAD

**Issue by Bdoom** [jenkinsci/ec2-fleet-plugin#309]
I copied the json for the IAM permissions from the jenkins plugin page and created an IAM role, followed the steps in order. However, no fleets for my spot instances are being populated in the select fleet dropdown. The plugin is broken.

**Comment by Bdoom** [comment]
![image](https://user-images.githubusercontent.com/1284431/141654615-2b8622cd-246c-43d1-8314-10a457a118b8.png)
Here is my fleet

Nothing shows in drop down menu:
![image](https://user-images.githubusercontent.com/1284431/141654627-53717e15-e72f-48e3-9763-b81805fa3a3a.png)


IAM Role:
![image](https://user-images.githubusercontent.com/1284431/141654660-de10680c-a857-45eb-8738-0526e26d1e0f.png)
![image](https://user-images.githubusercontent.com/1284431/141654668-a929f64a-13fc-4a3b-8624-9d220dee1a67.png)
![image](https://user-images.githubusercontent.com/1284431/141654673-763831f5-ecdb-4c2f-a913-866c3465efa4.png)

When I click test connection it says this even though the previous images show that I have permissions setup:
![image](https://user-images.githubusercontent.com/1284431/141654688-1338391a-b218-46ba-be66-0864fc031568.png)

**Comment by Bdoom** [comment]
I got it working now. I created a brand new user in IAM and added the policy. I'm assuming the policies might have conflicted or something? Still seems like a bug to me.

**Comment by imuqtadir** [comment]
After you got it working, is there a difference between the working IAM policies and the policies provided in instructions?

**Comment by imuqtadir** [comment]
I tested the policy and it seems fine. Feel free to reopen the issue if you encounter it again.
