### ISSUE TITLE
Control which availability zones the spots are requested at

### ISSUE THREAD

**Issue by dudaco** [jenkinsci/ec2-fleet-plugin#317]
**Is your feature request related to a problem? Please describe.**
Currently our jenkins configured to request spots from us-east-1 region and when it tries to request more instances we receive this issue: launchSpecUnusable c5.2xlarge ami-xxxxx, Linux/UNIX, us-east-1e, requested instance type is not supported in the requested Availability Zone.

the us-east-1e availability zone is not even configured on the spot-fleet subnets and i cant modify the jenkins request to exclude it.

**Describe the solution you'd like**
my suggestion is making the request without specifying any availability zone and let aws start a spot instance anywhere that's available or an option to choose which availability zones i would like to make the requests at.

**Comment by haugenj** [comment]
Can you elaborate on how you created/configured your spot fleet? AFAIK the plugin will only try to increment the fleet so it does not include any information regrading which az an instance would launch in
