### ISSUE TITLE
Add support for inbound agents

### ISSUE THREAD

**Issue by hoshsadiq** [jenkinsci/ec2-fleet-plugin#320]
**Is your feature request related to a problem? Please describe.**
We're trying to get Jenkins controller to connect to FIPS 140-2 compliant hosts as agents. This seems to be an issue with the ssh client Jenkins but I'm struggling to actually figure out where and why this is happening or where we could fix this.

Regardless of the above, FIPS compliance related issues seems to be a little deeper from what we understand.

**Describe the solution you'd like**
We'd like to be able to set up our agents so that we can use the inbound agent as opposed to the Jenkins controller connecting to the agents. This option exists for agents not controlled by ec2-fleet plugin.

For example, below screenshot is for a permanent agent
![Screenshot from 2022-01-14 17-51-24](https://user-images.githubusercontent.com/600045/149562157-dfe4d8b4-9ccf-435e-b9a9-075e6d638d3e.png)

Whereas below are the options the ec2-fleet plugin provides
![Screenshot from 2022-01-14 17-54-23](https://user-images.githubusercontent.com/600045/149562395-4cc5b8d6-5d16-46f8-a018-ecafcb661ae8.png)

**Describe alternatives you've considered**
None, I've struggling to find an alternative for our problem.

**Additional context**
I'm not sure how the secret can be handled for an inbound agent, however, from the top of my head, it might be possible to add the secret to SSM parameter under a specific path with the host id in the path as well, which could then be read by the instance.

**Comment by hoshsadiq** [comment]
As an alternative, AWS SSM Session Manager would be great. Being able to skip SSH key management would be great!

**Comment by imuqtadir** [comment]
This seems to be a bit more specific ask for your use-case. We usually prioritize issues based off general public use-cases/demand however we welcome PRs. Feel free to open a PR and we could help merge these in. Alternatively, I can keep the issue open to gauge public interest on this and prioritize it when we have enough users asking for this.
