### ISSUE TITLE
Removing outdated terminology

### ISSUE THREAD

**Issue by darthkisling** [jenkinsci/ec2-fleet-plugin#329]
Overall the tech community has made good strides to eliminate the unnecessary and harmful language associated with Master and Slave terminology. In most areas it seems like Jenkins has done a good job with this. I did notice though on the node status page there is a still a reference to "slave" seen as:

 Agent i-******** (Fleet slave for i-*************)

Can we please remove this terminology?

**Comment by imuqtadir** [comment]
Agreed. We welcome PRs from the community, feel free to submit a PR and we can help get it pushed. Alternatively, we will take it up while we prioritize the issues.

**Comment by naraharip2017** [comment]
Removed outdated terminology as part of https://github.com/jenkinsci/ec2-fleet-plugin/pull/386 where available. There is still `slave` references related to jenkins libraries and web urls, which will required updates outside of the plug-in to fix, and will address as those are updated

**Comment by pdk27** [comment]
Released in [ec2-fleet-2.7.1](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-2.7.1)
