### ISSUE TITLE
EC2 instance termination using AutoScaling group

### ISSUE THREAD

**Issue by valerypiotukh** [jenkinsci/ec2-fleet-plugin#332]
## Issue Details

Hi all, today I set up plugin with ASG (see screenshots below), execute Jenkins job like
```
node ('ec2-fleet') { 
  # scripted pipeline 
}
``` 
but my EC2 instance that is labled `ec2-fleet` is terminating after ~5-7 mins after job is starting (and no matter idle it or not)

<img width="700" alt="Screenshot 2022-04-12 at 18 11 49" src="https://user-images.githubusercontent.com/92525711/162995217-0ede57bf-042e-4bbd-910a-2004bf186bdb.png">

<img width="688" alt="Screenshot 2022-04-12 at 18 12 00" src="https://user-images.githubusercontent.com/92525711/162995298-e8101313-b22c-4b10-aa9e-6d589a0c415c.png">

<img width="673" alt="Screenshot 2022-04-12 at 18 12 12" src="https://user-images.githubusercontent.com/92525711/162995353-b76da492-25bf-4351-84fb-8577de015756.png">

<img width="680" alt="Screenshot 2022-04-12 at 18 12 20" src="https://user-images.githubusercontent.com/92525711/162995371-deb3bb3f-8f74-4abc-b34a-41adefc463e0.png">

Here's some logs when EC2 is terminating and starting again

> 2022-04-12 14:28:56.927+0000 [id=42]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: ec2-fleet [ec2-fleet] Set target capacity to '1'
> 2022-04-12 14:28:57.010+0000 [id=42]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: ec2-fleet [ec2-fleet] Fleet 'ec2-fleet' no longer has the instance 'i-026a4becc2b5040a6'. Removing instance from Jenkins
> 2022-04-12 14:28:57.011+0000 [id=484460]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: DISCONNECTED: ec2-fleet i-026a4becc2b5040a6
> 2022-04-12 14:28:57.011+0000 [id=484460]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Start retriggering executors for ec2-fleet i-026a4becc2b5040a6
> 2022-04-12 14:28:57.013+0000 [id=42]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: ec2-fleet [ec2-fleet] Skipping label update, the Jenkins node for instance 'i-026a4becc2b5040a6' was null
> 2022-04-12 14:28:57.013+0000 [id=484460]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: RETRIGGERING: org.jenkinsci.plugins.workflow.job.WorkflowJob@30f13dac[jenkins-job] - WITH ACTIONS: [hudson.model.ParametersAction@702d4591]
> 2022-04-12 14:28:57.014+0000 [id=484647]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: DISCONNECTED: ec2-fleet i-026a4becc2b5040a6
> 2022-04-12 14:28:57.014+0000 [id=484460]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Finished retriggering executors for ec2-fleet i-026a4becc2b5040a6
> 2022-04-12 14:28:57.014+0000 [id=484647]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Start retriggering executors for ec2-fleet i-026a4becc2b5040a6
> 2022-04-12 14:28:57.015+0000 [id=484647]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: RETRIGGERING: org.jenkinsci.plugins.workflow.job.WorkflowJob@30f13dac[jenkins-job] - WITH ACTIONS: [hudson.model.ParametersAction@702d4591]
> 2022-04-12 14:28:57.016+0000 [id=484647]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Finished retriggering executors for ec2-fleet i-026a4becc2b5040a6
> 2022-04-12 14:28:57.086+0000 [id=484552]	INFO	o.j.p.workflow.job.WorkflowRun#finish: jenkins-job #89 completed: ABORTED
> 2022-04-12 14:29:09.906+0000 [id=484693]	WARNING	o.j.plugins.builduser.BuildUser#handleOtherCausesOrLogWarningIfUnhandled: Unsupported cause type(s): []
> 2022-04-12 14:29:10.537+0000 [id=484293]	WARNING	o.j.plugins.builduser.BuildUser#handleOtherCausesOrLogWarningIfUnhandled: Unsupported cause type(s): []
> 2022-04-12 14:29:10.540+0000 [id=484711]	INFO	j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for ExecutorStepExecution.PlaceholderTask{runId=jenkins-job#90,label=ec2-fleet,context=CpsStepContext[3:node]:Owner[jenkins-job/90:jenkins-job #90],cookie=null,auth=null}:
> 2022-04-12 14:29:14.904+0000 [id=34]	INFO	j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for ExecutorStepExecution.PlaceholderTask{runId=jenkins-job#90,label=ec2-fleet,context=CpsStepContext[3:node]:Owner[jenkins-job/90:jenkins-job #90],cookie=null,auth=null}:
> 2022-04-12 14:29:18.212+0000 [id=34]	INFO	c.a.j.e.NoDelayProvisionStrategy#apply: label [ec2-fleet]: currentDemand 1 availableCapacity 0 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)
> 2022-04-12 14:29:18.213+0000 [id=34]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: ec2-fleet [ec2-fleet] Max instance size '1' reached. Skipping provision
> 2022-04-12 14:29:19.905+0000 [id=35]	INFO	j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for ExecutorStepExecution.PlaceholderTask{runId=jenkins-job#90,label=ec2-fleet,context=CpsStepContext[3:node]:Owner[jenkins-job/90:jenkins-job #90],cookie=null,auth=null}:

## Environment Details

**Plugin Version?**
2.5.1

**Jenkins Version?**
2.320

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
NO

**Linux or Windows?**
Linux

**Anything else unique about your setup?**

We use IAM role for the EC2 with jenkins like

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:*"
            ],
            "Resource": "arn:aws:autoscaling:region:AccID:autoScalingGroup:*:autoScalingGroupName/ASGName"
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeSpotFleetRequests",
                "ec2:DescribeSpotFleetInstances",
                "ec2:ModifySpotFleetRequest"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Resource": "arn:aws:ec2:region:AccID:instance/*",
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/aws:autoscaling:groupName": "tag"
                }
            }
        }
    ]
}

**Comment by haugenj** [comment]
From the logs it seems that the instance was terminated outside of the plugin's control. Can you check cloudtrail to see what caused the instance to be terminated?

**Comment by valerypiotukh** [comment]
@haugenj seems like the instance was terminated by plugin

>  "eventTime": "2022-04-12T20:28:54Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "TerminateInstances",
    "awsRegion": "region",
    "sourceIPAddress": "Public_IP",
    "userAgent": "ec2-fleet-plugin, aws-sdk-java/1.12.163 Linux/5.11.0-1022-aws OpenJDK_64-Bit_Server_VM/11.0.14.1+1 java/11.0.14.1 groovy/2.4.21 vendor/Eclipse_Adoptium cfg/retry-mode/legacy",
    "requestParameters": {
        "instancesSet": {
            "items": [
                {
                    "instanceId": "Instance_ID"
                }
            ]
        }
    },
    "responseElements": {
        "requestId": "8c173ef7-3235-414f-8be6-9e7f879467fd",
        "instancesSet": {
            "items": [
                {
                    "instanceId": "Instance_ID",
                    "currentState": {
                        "code": 32,
                        "name": "shutting-down"
                    },
                    "previousState": {
                        "code": 16,
                        "name": "running"
                    }
                }
            ]
        }
    }

**Comment by valerypiotukh** [comment]
From CloudTrail or from Jenkins logs?

**Comment by haugenj** [comment]
from Jenkins logs

**Comment by glavoie** [comment]
I've hit a potentially similar problem. Which looks like a timing problem.

- 2 instances fleet.
- Plugin sends the ASG size change 2 -> 1
- Plugin sends termination signal for instance 2
- ASG picks the change, selects instance 1 for termination
- Instance 1 is terminated and a build job that was running is killed
- Instance 2 is terminated.
- Fleet now has 0 nodes.
- ASG detect that it needs 1 node and scales up a new one. 


<img width="1414" alt="image" src="https://user-images.githubusercontent.com/13800915/175389465-3afadcf8-89fc-473e-a1cf-b9c67775bb1f.png">
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/13800915/175389639-edc0755a-9baf-4ba9-af56-2dad4a6a7691.png">
