### ISSUE TITLE
Add support for EC2 Fleets (not only Spot Fleets and ASGs)

### ISSUE THREAD

**Issue by pbudzon** [jenkinsci/ec2-fleet-plugin#336]
**Is your feature request related to a problem? Please describe.**
AWS is abandoning Spot Fleets and recommending use of EC2 Fleets. 

**Describe the solution you'd like**
Add support for EC2 Fleets alongside the current Spot Fleets and Auto Scaling groups.

**Describe alternatives you've considered**
None

**Additional context**
As far as I can tell, EC2 fleets are Spot Fleets with more features. The main difference would probably be using https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyFleet.html instead of ModifySpotFleetRequest. 

ModifyFleet allows for scaling based on vCPUs required (not only number of instances) which could be translated into jenkins executors somewhere down the road?

**References**
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotFleet.html
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-best-practices.html#which-spot-request-method-to-use

**Comment by fluffysquirrels** [comment]
We also would like to see this feature to use the plugin.
