### ISSUE TITLE
Apply Label on Jenkins Plugin Page

### ISSUE THREAD

**Issue by phreakadelle** [jenkinsci/ec2-fleet-plugin#34]
Hey guys, wouldnt it be useful to label your jenkins plugin properly? If this is a "Cloud Provider" plugin it should also have the label, like for example the "Docker Plugin".

https://plugins.jenkins.io/ec2-fleet
https://plugins.jenkins.io/docker-plugin

**Comment by terma** [comment]
Thx for point, ```plugin-cluster``` and ```plugin-cloud``` labels were added https://wiki.jenkins.io/label/JENKINS/plugin-cluster
