### ISSUE TITLE
Applying configuration changes on the fly

### ISSUE THREAD

**Issue by h-okon** [jenkinsci/ec2-fleet-plugin#346]
When using the plugin in the production environment, changing the options of the plugin should be supported without the need of restart of the jenkins instance (and reload of the plugin). Currently the plugin does not respect the new configuration and often rescales the fleets to wrong sizes, causing issues with builds.

Ultimately we would like the plugin to apply the configuration _on the fly_. Meaning that we would be able to change the configuration and within given timespan expect it to be applied gradually.  If there is a configuration change - the plugin will notice it and will calculate the difference in the parameters of each fleet. If there are changes in scaling - they should be applied gradually.

Alternatively (and the other known workaround) is to restart Jenkins instance to apply configuration. This however excludes **any** configuration changes in working hours as restarting Jenkins as you may imagine will disturb normal operations.

**Comment by benipeled** [comment]
@pdk27 please re-open and apply the "stalebot-ignore" label
