### ISSUE TITLE
Plugin auto select the first option from EC2 Fleet list

### ISSUE THREAD

**Issue by buliverd53** [jenkinsci/ec2-fleet-plugin#347]
## Issue Details

**Describe the bug**
If the spot-fleet or ASG is removed from the AWS Account, the cloud configuration auto select the first option from the **EC2 Fleet**.
From my point of view, the default value for this option should be blank so the team responsible for maintaining those fleet can see that a required option is missing.

**To Reproduce**
1. Remove a spot-fleet/asg configured for use on Cloud Configurations in Jenkins Nodes
2. Remove the spot-fleet/asg from the AWS Account
3. Open the Cloud Configuration on Jenkins 

## Environment Details

**Plugin Version?**
2.5.2

**Jenkins Version?**
2.374

**Spot Fleet or ASG?**
Spot Fleet and ASG

**Label based fleet?**
Yes

**Linux or Windows?**
Linux

**Anything else unique about your setup?**
No

**Comment by naraharip2017** [comment]
Issues addressed as part of https://github.com/jenkinsci/ec2-fleet-plugin/pull/385. Please, re-open if experiencing any additional issues.

**Comment by pdk27** [comment]
Released in [ec2-fleet-2.7.1](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-2.7.1)
