### ISSUE TITLE
plugin starts two times more instances than needed

### ISSUE THREAD

**Issue by delgod** [jenkinsci/ec2-fleet-plugin#35]
Hi

I have zero as Minimum Cluster Size.
I have eight different EC2 Fleet clouds with one executer per node.
When I start a job which requires only 96 nodes, I  get ~142 nodes up.
The situation happens only when I have 0 running instances before job running.

**Comment by delgod** [comment]
possible solution - https://github.com/jenkinsci/ec2-fleet-plugin/pull/29

**Comment by terma** [comment]
Release [1.4.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.4.0) includes a feature to add slaves into Jenkins only when EC2 instance state is actually ```running```, it's should reduce the number of overprovision slaves. Just go into Jenkins configuration and enable ```Only running instances```

It's a feature under testing, feedback is welcome, thx

**Comment by terma** [comment]
going to close, please add comments if any into #76, thx
