### ISSUE TITLE
If a Jenkins agent crashes, ec2-fleet doesn't terminate the agent, and we're stuck with a dead agent

### ISSUE THREAD

**Issue by keoren3** [jenkinsci/ec2-fleet-plugin#358]
## Issue Details

**Describe the bug**
We have an EC2-Fleet that holds a few agents, once an agent crashes (Due to bad code, and not terminated by AWS), Jenkins marks the agent as 'Unable to connect', but the agent stays in the fleet, and is actually holding a spot in the fleet.
We can have 4 out of 5 crashed agents, the EC2 fleet won't terminate the dead agents, and won't raise any new ones.

**To Reproduce**
1. Create an EC2 fleet that is made from an ASG with Spot instances in AWS.
2. Cause one agent to crash in the middle of the pipeline.
3. See how the agent keeps taking a place in the fleet.

## Environment Details

**Plugin Version?**
2.5.2

**Jenkins Version?**
2.361.3

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**
``
  clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      awsCredentialsId: "aws-jenkins-agent"
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "ec2-devops"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      disableTaskResubmit: false
      fleet: "JenkinsAgentsAS"
      idleMinutes: 1
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "ec2-fleet"
      maxSize: 20
      maxTotalUses: -1
      minSize: 5
      minSpareSize: 1
      name: "AutoScalingGroupAgents"
      noDelayProvision: true
      numExecutors: 1
      oldId: ""
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: false
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      awsCredentialsId: "aws-jenkins-agent"
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "ec2-devops"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      disableTaskResubmit: false
      fleet: "JenkinsAgentsAS_big_machines"
      idleMinutes: 1
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "big-machine"
      maxSize: 10
      maxTotalUses: -1
      minSize: 5
      minSpareSize: 0
      name: "AutoScalingGroupAgentsBigMachines"
      noDelayProvision: true
      numExecutors: 1
      oldId: ""
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      awsCredentialsId: "aws-jenkins-agent"
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "ec2-devops"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      disableTaskResubmit: false
      fleet: "JenkinsAgentsAS_very_small_machines"
      idleMinutes: 1
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "small-machine"
      maxSize: 10
      maxTotalUses: -1
      minSize: 1
      minSpareSize: 0
      name: "AutoScalingGroupAgentsSmallMachines"
      noDelayProvision: true
      numExecutors: 3
      oldId: ""
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
``

**Anything else unique about your setup?**
No

**Comment by keoren3** [comment]
If anyone encounters this, I was able to create a simple workaround.
I created a Python job that checks which agents are offline (Via Jenkins's API), and creates a list of EC2 Id's.
Then it sends a terminate command to AWS to terminate those instance ID's.
Once the instances are terminated the EC2 fleet is able to raise new ones, and doesn't get stuck with dead instances.

This jobs runs on a very small agent, every 5 minutes.

**Comment by oneumyvakin** [comment]
Looks like we also got into this issue.

**Comment by pdk27** [comment]
@keoren3 @oneumyvakin Can you upgrade to the [ec2-fleet-2.7.1 ](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-2.7.1) and update the issue with logs? The recent versions include some changes related to plugin initiated terminations and I am hoping the logs can help us troubleshoot your issue. 

Here are the [reasons](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2AgentTerminationReason.java#L7-L10) why the plugin would terminate an instance today. If the terminated instance was idle and the plugin missed terminating it, then this particular issue is fixed. See [related issue for explanation](https://github.com/jenkinsci/ec2-fleet-plugin/issues/322#issuecomment-1611941796).

**Comment by pdk27** [comment]
This issue might be fixed. Closing due to lack of recent activity. Please re-open if the issue still exists.
