### ISSUE TITLE
EC2FleetCloud constructor blindly reassigns fleets

### ISSUE THREAD

**Issue by wzur-r3** [jenkinsci/ec2-fleet-plugin#360]
We use Jenkins Configuration as a Code a lot, and amongst other things it creates throw-away objects to get and dump configuration in YAML format.

This line https://github.com/jenkinsci/ec2-fleet-plugin/blob/69dcf230ed6953436675f28a50efab6ca7b3d111/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java#L225 introduced a side effect of reassigning cloud aware nodes and computers to a new `EC2FleetCloud` object. That throw-away object created by JCasC is put into all matching cloud aware nodes, but the list of clouds maintained by Jenkins stays the same.

That leads to EC2 Fleet cloud objects attached to nodes checked their status, which was saved within these objects, however `CloudNanny` would use different objects, albeit with the same `cloudId`. So we ended up with nodes marked for deletion in one Java thread, and thus suspended, but they would never actually deleted, because the list of nodes to delete checked by `CloudNanny` thread was empty, as it was hold by a different fleet object.

**Comment by wzur-r3** [comment]
I can see that was to fix #302, but that fix is as bad and moved problems to a different place in the code

**Comment by mwos-sl** [comment]
Similar issue mentioned here: https://github.com/jenkinsci/ec2-fleet-plugin/issues/322#issuecomment-1372398033

**Comment by icep87** [comment]
Similar issue #374

**Comment by icep87** [comment]
@pdk27 Any progress on this?

**Comment by pdk27** [comment]
Still working on this. The changes to fix this issue involves quite a bit of refactoring and removing code. So, prioritized getting a release out to fix a few long-standing issues first. 
We should be able to get the PRs out this week and a release will follow.

**Comment by limasilet** [comment]
Hitting this error as well. Glad to see the plugin being updated. Thanks!
