### ISSUE TITLE
Connect to instances via AWS SSM

### ISSUE THREAD

**Issue by HardHero** [jenkinsci/ec2-fleet-plugin#398]
**Is your feature request related to a problem? Please describe.**
We use the AWS SSM Sessions in place of most actual ssh connections in our infrastructure. It would be nice if there was a selection under `Launcher` to "Connect Via SSM".

**Describe the solution you'd like**
As described above, a `Launcher` option to "Connect via SSM".

**Describe alternatives you've considered**
I have been trying to get it working with a Custom command like `INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values='temp'" --query 'sort_by(Reservations[].Instances[], &LaunchTime)[].[InstanceId]' --output text| tail -1) && aws ssm start-session --target $INSTANCE_ID` but to no good outcome.

**Comment by henrykie** [comment]
I would also love to see this feature!

**Comment by gabebatista** [comment]
This feature would be helpful to me as well
