### ISSUE TITLE
Delay running jobs on node until cloud-init is finished

### ISSUE THREAD

**Issue by pbudzon** [jenkinsci/ec2-fleet-plugin#407]
**Is your feature request related to a problem? Please describe.**
We use ASGs and we have user-data configured to do some basic setup on the nodes when they start (takes a couple of seconds, puts some configs in some files). However, we noticed that jenkins will start using the node before cloud-init is finished and so before our configs are in place, which causes the jobs to fail. The full cloud-init run takes a moment, since it does a bunch of other stuff internally before it gets to user-data scripts.

**Describe the solution you'd like**
Add a "delay" parameter to cloud config that will make Jenkins wait the specific amount of time before using the node (either before or after connecting to it). 
Or (and that would be perfect) wait until cloud-init finishes before using the node. Though I have no clue if there's an easy way to tell when it's done?

**Describe alternatives you've considered**
We will bake in our configs into the AMI we use for launching the nodes. It's less flexible but will work for now.

**Comment by pdk27** [comment]
@pbudzon Have you tried [this](https://github.com/jenkinsci/ec2-fleet-plugin#ssh-prefix-verification)? I believe it is a good alternative for your use case. Feel free to re-open if it isn't.
