### ISSUE TITLE
Upgrading 3.0.1 to 3.1.0 deleted cloud configuration

### ISSUE THREAD

**Issue by silentgamesstudio-rpc** [jenkinsci/ec2-fleet-plugin#421]
## Issue Details

Upon upgrading from 3.0.1 to 3.1.0 our cloud configuration was deleted. The `Manage Jenkins`->`Clouds` page showed the message "There are no clouds currently setup" and the `<clouds>` section of config.xml was replaced by an empty `<clouds/>` tag.

Rolling back the plugin to 3.0.1 and restoring config.xml from backup worked around the issue.

## Environment Details

**Plugin Version?**
3.1.0

**Jenkins Version?**
2.414.3

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Linux or Windows?**
Windows

**EC2Fleet Configuration as Code**
N/A

**Anything else unique about your setup?**
No

**Comment by Hildebrand-Ritense** [comment]
yes, same here. Had to roll back the update and restore the config from a backup. This was on jenkins 2.416 on an Amazon Linux instance. ASG fleet + labels. Nothing special.

**Comment by CaptainDonut** [comment]
Same issue here, it removed my config and had to roll back for it to work. 2.416 on Amazon Linux.

**Comment by silentgamesstudio-rpc** [comment]
Looks like #423 might fix this

**Comment by JonnyPower** [comment]
This is quite an unbelievable rollout - so we are to accept deletion of our cloud configuration simply due to an update?

**Comment by davorceman** [comment]
Same here. Jenkins version 2.426.1

**Comment by JonnyPower** [comment]
Thanks @GavinBurris42 - we appreciate your plugin and your work maintaining it, apologies for being testy - looking forward to updating :)

**Comment by ilievlad** [comment]
I had the same issue with upgrade from 3.1.0 to 3.2.0

I recreated the clouds in 3.1.0 because I lost them on upgrade then.

**Comment by phillipuniverse** [comment]
@GavinBurris42 I came in late to this issue, only when my upgrade from 3.1.0 -> 3.2.0 also hosed my ec2-fleet configuration. Sadly I didn't learn my lesson when 3.0 -> 3.1 also hosed it!

I think it would be better if there was a really big warning on the upgrade that this would show that all clouds were deleted in the UI, and that users needed to take a backup of `config.xml` before continuing.
