### ISSUE TITLE
Complete  removal of data about the Executors structure 3.0.2 --> 3.1.0

### ISSUE THREAD

**Issue by vadbosh** [jenkinsci/ec2-fleet-plugin#422]
## Issue Details

Complete removal of data about the Executors structure
The correct config from the backup is forcibly deleted

**Describe the bug**

**To Reproduce**
1.  3.0.2 update to 3.1.0
2. 
etc.

** Logs **
Tip: See [this guide](https://www.jenkins.io/doc/book/system-administration/viewing-logs/#logs-in-jenkins) to configure a logger in Jenkins UI. Please attach `fine` logs if you think they are relevant.

## Environment Details

**Plugin Version?**
3.1.0

**Jenkins Version?**
2.414.3

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
Yes

**Linux or Windows?**
Linux (Ubuntu 20.04 LTS)

**EC2Fleet Configuration as Code**
``
Paste only eC2Fleet part from plugin configuration. Mask all security concerning details. You can download it from Manage Jenkins > Configuration as Code > Download Configuration
``

**Anything else unique about your setup?**
Yes
Jenkins start options 
/usr/bin/java -Djava.awt.headless=true -Xms512m -Xmx5096m -XX:+AlwaysPreTouch -XX:+UseParallelGC -XX:+UseAdaptiveSizePolicy -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080

**Comment by nleck** [comment]
The 3.1.0 plugin seems to be completely broken.

**Comment by GavinBurris42** [comment]
This issue arose from class name changes which affected the instantiation of clouds from the config.xml file. This is resolved in Release [ec2-fleet-3.2.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-3.2.0)
