### ISSUE TITLE
Protected From Scale In

### ISSUE THREAD

**Issue by sagarnitd** [jenkinsci/ec2-fleet-plugin#430]
Issue Description:

I have encountered a recurring problem where the "protectedfromscalein" setting gets reset repeatedly, disrupting the functionality of dynamic scaling policies. Despite my attempts to disable this setting, it appears to revert to its default state, preventing the effective implementation of dynamic scaling.

Impact:

This issue is hindering the proper utilization of dynamic scaling policies, affecting the scalability and responsiveness of the system.

Steps to Reproduce:

Attempt to disable "protectedfromscalein."
Observe the setting being reset to its default state.

Expected Behavior:

The "protectedfromscalein" setting should persistently reflect the user's configuration choices and not reset unexpectedly.

Additional Information:

System/environment details
Any recent changes or updates that may be related

Request for Resolution:

I kindly request assistance in investigating and resolving this issue to ensure dynamic scaling policies' stable and consistent functioning.

Thank you for your attention to this matter.

**Comment by antikaspar** [comment]
Where do you set the scale-in protection? In the AWS CLI/UI or by IaC tooling? Maybe an conflict between these two?

**Comment by ajax-koval-i** [comment]
have the same issue.
I do not have IaC tooling. ASG was created via AWS Management Console.

JFYI @antikaspar @sagarnitd

**Comment by pawel-t** [comment]
I observe the same issue on my side. IaC is disabling this option, but then plugin enables it and instances are not scaling down.

**Comment by sagarnitd** [comment]
The best option is to set minimum = 0 and scale down minutes to 10 or 15.
