### ISSUE TITLE
Use instance profile for credentials

### ISSUE THREAD

**Issue by grahamhar** [jenkinsci/ec2-fleet-plugin#44]
When running Jenkins instance on an EC2 instance with an instance profile attached I should have the option of not providing hard coded AWS credentials. Is this a possibility?

**Comment by schmutze** [comment]
You can just leave the creds blank if you are using EC2 instance roles and it will work. Please test and confirm your experience.

**Comment by grahamhar** [comment]
@schmutze thanks for the fast response. I'm not having much luck, but I think it is down to my misunderstanding. From the name I assumed it used ec2-fleet (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-fleet.html)  but I think on reflection it is just using spot fleet (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html)

**Comment by schmutze** [comment]
Check out the instance roles in this cfn template:
https://github.com/awslabs/ec2-spot-labs/blob/master/ec2-spot-fleet-jenkins-plugin/spot-fleet-jenkins-plugin.yaml

**Comment by schmutze** [comment]
Yes the Jenkins plugin uses Spot Fleet, not EC2 Fleet (although they are essentially the same API with a different name).

**Comment by grahamhar** [comment]
@schmutze thanks for taking the time to help. I've just created a spot fleet and it now appears in the list, the one I created using ec2-fleet didn't. If I get time tomorrow I'll do a PR to add something to the readme to make this a bit clear. What do you think?

**Comment by schmutze** [comment]
Sounds good, thank you. As everyone knows I'm a bit slow around here but I *am* here. :)
