### ISSUE TITLE
Terminate nodes if not online within X minutes

### ISSUE THREAD

**Issue by bertjwregeer** [jenkinsci/ec2-fleet-plugin#47]
I'm using cloud-init to bring my nodes online, however every so often when they reboot after doing the package installation/upgrades the system won't come back online due to issues with NVMe or some other error.

In those cases instead of considering them up because they are up according to Amazon it would be neat if the instance is terminated with prejudice so that Amazon can kick over a new instance to replace it.

This doesn't happen often, but not needing to manually do this would be fantastic!

My nodes should come online within 5 - 10 minutes, if they still aren't doing work by then, shoot em in the head.

**Comment by terma** [comment]
Are those nodes marked in Jenkins as offline, because Jenkins is not able to connect to them?

**Comment by bertjwregeer** [comment]
Yes, they are marked offline because Jenkins is unable to connect to them.

**Comment by bertjwregeer** [comment]
In fact, nothing can connect to them because they can't finish booting. I don't necessarily understand why it happens, but every so often after a reboot the node can't find it's NVMe disks and mounting fails, and systemd just hangs at the console.

**Comment by terma** [comment]
Interesting, so possible feature could be: identify if node is offline and created by EC2 Fleet plugin, if so, terminate them from plugin, EC2 Fleet API can provide new one. Is that correct?

**Comment by bertjwregeer** [comment]
Yes.

Right now it's a manual step, I notice that one of the executors doesn't come online, I go into the ec2 console, find the machine, and terminate it. Ec2 will automatically start a new one to replace the one I just terminated, to get to the spot fleet requests number.

**Comment by terma** [comment]
@bertjwregeer have you tried to use ```Replace unhealthy instances``` feature from EC2 Spot? 

To try, during requesting Spot click ```Additional configurations``` and you will see section ```Health check``` with ```Replace unhealthy instances``` checkbox, unchecked by default (make sure you ```Maintain target capacity``` is enabled for Spot Fleet. 

According to [instance check](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-system-instance-status-check.html) it should automatically replace bad instances in a few min.

**Comment by bertjwregeer** [comment]
Instance checking and replace unhealthy instances is enabled, but I am not seeing unhealthy nodes killed at all.

I'll do some more investigation of the setting and see if I can figure out why it's not working.

**Comment by terma** [comment]
@bertjwregeer I made some investigation, it's EC2 Spot issue if ```Health check``` is enabled. I suggest you to open customer ticket https://aws.amazon.com/contact-us/ when you see this issue again. I think it's better then additing some checking logic on Plugin side as it doesn't have full picture of why it ```offline```.

**Comment by imuqtadir** [comment]
I think this should be resolved with some of our latest changes like being able to terminate EC2 instances from Jenkins dashboard directly. Please let us know if you still experience this issue and if there is anything left here which could be further improved.
