### ISSUE TITLE
how does ec2-fleet resolve the known_hosts issue?

### ISSUE THREAD

**Issue by deitch** [jenkinsci/ec2-fleet-plugin#48]
Thanks to both awslabs and jenkins for a great plugin.

If I add an agent using ssh-slave (which ec2-fleet uses), I need to ensure that:

1. The master's ssh public key is in `$JENKINS_HOME/.ssh/authorized_keys` on the agent (or passed via param or env var for the docker image)
2. The agent's host key is in `$JENKINS_HOME/.ssh/known_hosts` on the master

The agent here is launched dynamically via ec2-fleet, so the host key for the new agent isn't known until _after_ the host launches, when Jenkins tries to connect.

How do you insert the (new) host key into `known_hosts`, and remove it when a node is deleted (important since IPs can be reused)? Or do most people take the insecure route and disable known hosts verification?

On the other side, how is the public key for the Jenkins master installed onto the spot instance? Is the assumption that I will set up a spot fleet, and configure it via userdata?

**Comment by deitch** [comment]
Got it, thanks @bertjwregeer . I think I still prefer being able to verify, but I don't see how. It would be nice in that respect if ssh worked like full ssl, with an x509 cert signed by a common authority. Then I wouldn't need the _actual_ host pubkey in `known_hosts`, just the cert of the signing authority. Oh well.

It actually has taken me a bit to "turn my head around" on this. Normally, when deploying scaling apps on aws, I use an autoscaling group, and have new "worker" nodes self-join a cluster. In the Jenkins case, I would use ASG (or possibly spot fleet) to spin up new workers and have them join Jenkins.

The challenges I found with that approach are:

1. It isn't sufficient to just "connect"; I need to "add" the new node using the Jenkins CLI or REST API as a "permanent" node, and then either retrieve the jnlp agent-specific secret and join, or use ssh (which creates the same issue with host key, although possibly more easily solvable if I am initiating from the host which already knows its host key). Solvable.
2. Deletion of hosts isn't automatic. If I have a node created by an ASG, it then might be terminated. Instead of Jenkins removing it (as happens, e.g. with Kubernetes and cloud-provider set to AWS), it lingers as an unreachable host. I could create a clean-up job, but that is just more custom work.
3. Deletion of hosts isn't "Jenkins-aware", i.e. it might delete a host that has a running job. Of course, the same thing can happen with spot fleet as well, so not as challenging.

The ec2-fleet plugin pretty much solves 2 & 3, and I can set the userdata or custom AMI (or use docker with custom OCI image) to resolve 1, as you mentioned.

Still and all, doing it _from_ the Jenkins Server via a plugin, rather than _from_ ASG, is a little different.

Any way to use jnlp instead of ssh for the spot fleet nodes?

**Comment by bertjwregeer** [comment]
@deitch SSH CAN work like that though. See https://jameshfisher.com/2018/03/16/how-to-create-an-ssh-certificate-authority.html for a guide on how to setup/configure that.

**Comment by deitch** [comment]
> SSH CAN work like that though

Quite! (and I am facepalming myself for not thinking of it...; thanks @bertjwregeer :-) )

Does the ssh implementation on the server side in jenkins ssh-slave support it? Or is it just exec-ing out to the on-host `ssh` client anyways?
