### ISSUE TITLE
Scaling down to zero instances works, but then won't scale back up

### ISSUE THREAD

**Issue by VackarAfzal** [jenkinsci/ec2-fleet-plugin#52]
When settings the min number of instances to zero, the plugin will successfully scale the instances down after the defined idle time. It doesn't however then scale up the desire size once job start coming in.

I've tested this with a build queue size of 1, 5, 10 and executors (per node) of 1 and 4

edit: Just to give some context, this only occurs when I have other nodes that I explicitly mark as offline. As soon as I delete the offline nodes, scaling works as expected.

**Comment by ianfixes** [comment]
I may have this problem as well

**Comment by ebalakumar** [comment]
@VackarAfzal  . In my case Target capacity and min size works weirdly  or please correct me if my understanding is wrong .  When I keep the Target capacity in jenkins as 2 and min size as 0 . It immediately sets the target capacity to two in the spot fleet when there is a job which does not require that much . is it supposed to create just one and scale up based on demand ???

**Comment by fruch** [comment]
happens to me as well, i'm using 0.1.15 version

Any idea which logs might help to solve this issue ? it's kind of a key feature for this plugin, i.e. don't waste money on idle spots, hence we want the min target to be 0

**Comment by terma** [comment]
Hi, @fruch do you have a problem during scale up or initial capacity? The original issue about scale up while comments about initial. Could you please provide your use case. Thx

**Comment by fruch** [comment]
My problem is that when I have a fleet target capacity set to 0, the plugin doesn't update the target capacity to what's to match the jobs waiting in the queue.
when I update the target manually, things start working.
but after the plugin set the target back to 0, its again doesn't scale back up on the next runs that need the label configured for the fleet

**Comment by terma** [comment]
Ok, got it, looks like existent issue #43 will close this one to keep single thread, feel free to reopen if you think it's diff. Thx.
