### ISSUE TITLE
@VackarAfzal  . In my case Target capacity and min size works weirdly  or please correct me if my understanding is wrong .  When I keep the Target capacity in jenkins as 2 and min size as 0 . It immediately sets the target capacity to two in the spot fleet when there is a job which does not require that much . is it supposed to create just one and scale up based on demand ???

### ISSUE THREAD

**Issue by ebalakumar** [jenkinsci/ec2-fleet-plugin#62]
@VackarAfzal  . In my case Target capacity and min size works weirdly  or please correct me if my understanding is wrong .  When I keep the Target capacity in jenkins as 2 and min size as 0 . It immediately sets the target capacity to two in the spot fleet when there is a job which does not require that much . is it supposed to create just one and scale up based on demand ???

_Originally posted by @ebalakumar in https://github.com/jenkinsci/ec2-fleet-plugin/issues/52#issuecomment-482520557_

**Comment by ebalakumar** [comment]
Jenkins : 
   Executors: 6
  Target capacity : 2
  Min size : 0
  Max size : 2

Spot Fleet : (m4.large , m5.large) When a job is scheduled in jenkins 2 instances are created . But that job may not require two instance . I am confused about this behavior .
1.  Is is supposed to spin just 1 instance at first and scale up/down based on demand. ?
2. Does it has to do with Executor set to 6 ?

**Comment by terma** [comment]
hi @ebalakumar

Below logic to scale up:
1. jenkins job scheduled
2. jenkins requests plugin for X executors (depends on jenkins not plugin, you probably can check if you have multi/parallel job which could require more then one executor)
1. plugin calculates amount of additional nodes, as requested number of executors devided by ```executors``` setting
1. plugin updates fleet ```targetCapacity```
1. create required amount of nodes in jenkins

Based on that and your numbers, and assume jenkins requrested ```<7```, it should request **only one node**

 You can check jenkins logs for ```Provisioning nodes. Excess workload``` what plugin decided internally

**Comment by imuqtadir** [comment]
I am assuming your question was answered. If not, please let us know.
