### ISSUE TITLE
How do you set per-node environment variables?

### ISSUE THREAD

**Issue by seantalts** [jenkinsci/ec2-fleet-plugin#63]
We're trying to set some Jenkins environment variables for use in our declarative pipeline for the spot fleet. We were trying to use the SSH agent command prefix to do so, and finding that it seems to randomly work sometimes and not work other times. In our case we just need to set some environment variables as being the same across all of the nodes in the fleet (but we have other hardware agents that have varying values for these environment variables). Is there a better way to do this? `/etc/profile` also doesn't seem to work reliably. Thanks!

**Comment by terma** [comment]
hi, @seantalts is that possible for you to use [UserData](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) which is some kind of script applied to host when EC2 launch it. You can configure it for EC2 Spot Fleet by creating [LaunchTemplate](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestLaunchTemplateData.html) with configured ```UserData``` and run EC2 Spot Fleet with this Launch Template.

**Comment by terma** [comment]
Closed, feel free to reopen if you have questions or comments. Thx.

**Comment by posilva** [comment]
@terma Why not following the same interface as other Jenkins Cloud Providers and allow to set the env variables using the Jenkins Ec2 Fleet configuration. 

Having to update the deployment to adjust an environment variable does not sound reasonable, once Jenkins is able to set environment variables in slaves already. 

What do you think?

Thanks for the great plugin.
