### ISSUE TITLE
Windows nodes not removed after termination

### ISSUE THREAD

**Issue by caneridge** [jenkinsci/ec2-fleet-plugin#9]
I started a spot fleet in AWS. The bidding went up to $15/hr for several hours. My max bid price was $1.50. All of the instances for my spot instance were terminated by AWS. In Jenkins, I had about 2 dozen dead instances that Jenkins failed to remove. I was able to remove the instances manually one at a time in Jenkins. Deleting the fleet configuration in Jenkins and restarting also removes the instances. The bug is that this plugin does not gracefully handle the case where AWS cancels all of the instances for the spot fleet and is unable to provision additional instances. The instances are marked as down in Jenkins and are not removed. This is currently happening for c3.2xlarge Windows which has been completely sold out for several hours in AWS today. It was not even possible to start an on-demand instance.

**Comment by terma** [comment]
Thx for report, fix was released under [1.1.8](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.1.8), feel free to reopen if any questions
