### ISSUE TITLE
Support auto-scaling fleets as well

### ISSUE THREAD

**Issue by jzila** [jenkinsci/ec2-fleet-plugin#98]
We're finding that AWS terminates our spot instances too often, which just kills our Jenkins builds.

It would be great if we could specify an auto-scaling fleet either as a backup for spot instances, or instead of the spot fleet.

For the time being I think we'll need to switch to the EC2 plugin, which isn't nearly as robust as this one.

**Comment by terma** [comment]
hi, probably could help. We have feature in progress, to get notification before spot instance will be terminate (spot send notification 2 min upfront) and gracefully stop using this node, in scope of #45 For first iteration it should totally reduce amount of red/interrupted builds as soon as their duration ```< 2 min```

Ping me if you have different use case or any questions, thx

**Comment by jzila** [comment]
That could work, although it'll still result in failed builds (red X's on GitHub).

And in periods of high instance utilization where the spot price gets higher than on demand, we get instance termination thrashing. E.g. desired count 16 and actual count ~5. Builds try to build, but instances get terminated often enough that no builds end up being able to get through, even with automatic restarts (which is what we instruct folks to do).

A backup auto-scaling group would allow fallback to instances that won't be terminated. Or if a fallback is too complicated, then just the option to switch to an autoscaling group would be good.

**Comment by terma** [comment]
btw you can use non zero on-demand capacity to your fleet. On-demand are regular EC2 instances (not Spot) as result you can configure some minimum capacity for fleet regarles of Spot price, for remain capacity fleet will use Spot instances. 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html#on-demand-in-spot

**Comment by jzila** [comment]
Hmm that's a great idea. Maybe this ticket can represent a configurable parameter for that?

**Comment by terma** [comment]
on-demand capacity is part of fleet configuration, you can set it only when you create fleet. Fleet doesn't support on-demand capacity modification =( however I think it's good point to add this as configuration example to ```README``` issue for that #100

**Comment by jzila** [comment]
Hmm in that case it's an okay band-aid, but it's not a long term solution. In fact we already do exactly this with a backup auto-scaling group for each spot fleet, but we just manually add those instances once.

Ideally I'd like an auto-scaling group of on-demand instances that scales with the same behavior as spot fleets do in this plugin.

**Comment by jzila** [comment]
In fact, refactoring this whole strategy to using auto-scaling groups with launch templates could allow much more flexibility with respect to combinations of on-demand and spot instances:

https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html

**Comment by terma** [comment]
yes, started to work on that.

**Comment by schmutze** [comment]
Hi @jzila - is your Spot Fleet well diversified (multiple instance types and multiple AZs)? Which allocation strategy are you using?

**Comment by jzila** [comment]
Our spot fleets have a single instance type for consistency (one fleet for Linux and one for Windows), but all AZs in a given region. We use the default `lowestPrice` allocation strategy.

**Comment by terma** [comment]
hi, I think #104 could help you, it allows EC2 Fleet Plugin auto re-submit failed (because of Spot interruption) jobs. As soon as it will be merged will update with plugin version. Thx.

**Comment by schmutze** [comment]
@jzila beyond the failed job re-submit that @terma is working on, qualifying additional instance types to use in your Spot Fleet and changing your allocation strategy to diversified over N lowest-priced pools would go a long way in adding stability to your environment. What would it take to qualify a few additional instance types?

**Comment by jzila** [comment]
> @jzila beyond the failed job re-submit that @terma is working on, qualifying additional instance types to use in your Spot Fleet and changing your allocation strategy to diversified over N lowest-priced pools would go a long way in adding stability to your environment. What would it take to qualify a few additional instance types?

I can go through the list and qualify a few more instance types. We mostly just need a lot of memory (16GB+), and preferably 4 ECUs. Thanks for the advice!

> hi, I think #104 could help you, it allows EC2 Fleet Plugin auto re-submit failed (because of Spot interruption) jobs. As soon as it will be merged will update with plugin version. Thx.

That might help, although as I mentioned we sometimes get thrashing when there are lots of terminations, and our builds take long enough to run that we often get to 100% starvation in such situations.

**Comment by terma** [comment]
Auto resubmit for failed jobs due to EC2 instance termination released under [1.7.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.7.0)

**Comment by jzila** [comment]
Thank you!

**Comment by terma** [comment]
Auto Scaling Group support was added in version [1.5.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.15.0), please make sure plugin has updated permissions for IAM User, thx

Going to close, feel free to reopen and comment if you see some problem or have questions.
